### ISSUE TITLE
Gettting Error: Failure

### ISSUE THREAD

**Issue by jenish-rudani** [Natizyskunk/vscode-sftp#15]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**
File not being transferred to Remote Device. Throws Following Error

[07-14 11:38:58] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[07-14 11:38:58] [debug] register command "Config" from "./commandConfig.ts"
[07-14 11:38:58] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[07-14 11:38:58] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[07-14 11:38:58] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[07-14 11:38:58] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[07-14 11:38:58] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[07-14 11:38:58] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[07-14 11:38:58] [debug] register command "Diff" from "./fileCommandDiff.ts"
[07-14 11:38:58] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[07-14 11:38:58] [debug] register command "Download" from "./fileCommandDownload.ts"
[07-14 11:38:58] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[07-14 11:38:58] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[07-14 11:38:58] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[07-14 11:38:58] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[07-14 11:38:58] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[07-14 11:38:58] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[07-14 11:38:58] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[07-14 11:38:58] [debug] register command "List" from "./fileCommandList.ts"
[07-14 11:38:58] [debug] register command "List All" from "./fileCommandListAll.ts"
[07-14 11:38:58] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[07-14 11:38:58] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[07-14 11:38:58] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[07-14 11:38:58] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[07-14 11:38:58] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[07-14 11:38:58] [debug] register command "Upload" from "./fileCommandUpload.ts"
[07-14 11:38:58] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[07-14 11:38:58] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[07-14 11:38:58] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[07-14 11:38:58] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[07-14 11:38:58] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[07-14 11:38:58] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[07-14 11:38:58] [info] config at /home/atom/Documents/Work/Code/github/mainDev {"remotePath":"/home/pi/vtt","uploadOnSave":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"pi","host":"192.168.0.106","port":22,"username":"******","password":"******"}
[07-14 11:39:00] [info] [file-save] /home/atom/Documents/Work/Code/github/mainDev/src/tof.py
[07-14 11:39:00] [trace] handle upload file for /home/atom/Documents/Work/Code/github/mainDev/src/tof.py
[07-14 11:39:00] [debug] Custom crypto binding not available
[07-14 11:39:00] [debug] Client: Trying 192.168.0.106 on port 22 ...
[07-14 11:39:00] [debug] Local ident: 'SSH-2.0-ssh2js1.1.0'
[07-14 11:39:00] [debug] Socket connected
[07-14 11:39:00] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.9p1 Raspbian-10+deb10u2+rpt1'
[07-14 11:39:00] [debug] Outbound: Sending KEXINIT
[07-14 11:39:00] [debug] Inbound: Handshake in progress
[07-14 11:39:00] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[07-14 11:39:00] [debug] Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
[07-14 11:39:00] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[07-14 11:39:00] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[07-14 11:39:00] [debug] Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
[07-14 11:39:00] [debug] Handshake: Host key format: ssh-ed25519
[07-14 11:39:00] [debug] Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[07-14 11:39:00] [debug] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[07-14 11:39:00] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[07-14 11:39:00] [debug] Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[07-14 11:39:00] [debug] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[07-14 11:39:00] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[07-14 11:39:00] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-14 11:39:00] [debug] Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-14 11:39:00] [debug] Handshake: C->S MAC: <implicit>
[07-14 11:39:00] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-14 11:39:00] [debug] Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-14 11:39:00] [debug] Handshake: S->C MAC: <implicit>
[07-14 11:39:00] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[07-14 11:39:00] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[07-14 11:39:00] [debug] Handshake: C->S compression: none
[07-14 11:39:00] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[07-14 11:39:00] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[07-14 11:39:00] [debug] Handshake: S->C compression: none
[07-14 11:39:00] [debug] Outbound: Sending KEXECDH_INIT
[07-14 11:39:00] [debug] Received DH Reply
[07-14 11:39:00] [debug] Host accepted by default (no verification)
[07-14 11:39:00] [debug] Host accepted (verified)
[07-14 11:39:00] [debug] Inbound: NEWKEYS
[07-14 11:39:00] [debug] Verifying signature ...
[07-14 11:39:00] [debug] Verified signature
[07-14 11:39:00] [debug] Outbound: Sending NEWKEYS
[07-14 11:39:00] [debug] Handshake completed
[07-14 11:39:00] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[07-14 11:39:00] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[07-14 11:39:00] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[07-14 11:39:00] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[07-14 11:39:00] [debug] Client: none auth failed
[07-14 11:39:00] [debug] Outbound: Sending USERAUTH_REQUEST (password)
[07-14 11:39:01] [debug] Inbound: Received USERAUTH_SUCCESS
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[07-14 11:39:01] [debug] Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
[07-14 11:39:01] [debug] Outbound: Sending REQUEST_FAILURE
[07-14 11:39:01] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[07-14 11:39:01] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[07-14 11:39:01] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[07-14 11:39:01] [debug] Inbound: CHANNEL_DATA (r:0, 154)
[07-14 11:39:01] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com)
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 33)
[07-14 11:39:01] [debug] SFTP: Outbound: Buffered MKDIR
[07-14 11:39:01] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[07-14 11:39:01] [debug] SFTP: Inbound: Received STATUS (id:0, 4, "Failure")
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 29)
[07-14 11:39:01] [debug] SFTP: Outbound: Buffered LSTAT
[07-14 11:39:01] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[07-14 11:39:01] [debug] SFTP: Inbound: Received ATTRS (id:1)
[07-14 11:39:01] [info] file transfered.
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 44)
[07-14 11:39:01] [debug] SFTP: Outbound: Buffered OPEN
[07-14 11:39:01] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[07-14 11:39:01] [debug] SFTP: Inbound: Received HANDLE (id:2)
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[07-14 11:39:01] [debug] SFTP: Outbound: Buffered FSTAT
[07-14 11:39:01] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[07-14 11:39:01] [debug] SFTP: Inbound: Received ATTRS (id:3)
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 25)
[07-14 11:39:01] [debug] SFTP: Outbound: Buffered FSETSTAT
[07-14 11:39:01] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[07-14 11:39:01] [debug] SFTP: Inbound: Received STATUS (id:4, 0, "Success")
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 4260)
[07-14 11:39:01] [debug] SFTP: Outbound: Sent WRITE (id:5)
[07-14 11:39:01] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[07-14 11:39:01] [debug] SFTP: Inbound: Received STATUS (id:5, 4, "Failure")
[07-14 11:39:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[07-14 11:39:01] [debug] SFTP: Outbound: Buffered CLOSE
[07-14 11:39:01] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[07-14 11:39:01] [debug] SFTP: Inbound: Received STATUS (id:6, 0, "Success")
[07-14 11:39:01] [error] Error: Failure
	at 101 (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/protocol/SFTP.js:2471:19)
	at SFTP.push (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/protocol/SFTP.js:271:11)
	at CHANNEL_DATA (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/client.js:505:23)
	at 94 (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/protocol/handlers.misc.js:841:16)
	at Protocol.onPayload (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/protocol/Protocol.js:1974:10)
	at AESGCMDecipherNative.decrypt (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/protocol/crypto.js:992:26)
	at Protocol.parsePacket [as _parse] (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/protocol/Protocol.js:1943:25)
	at Protocol.parse (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/protocol/Protocol.js:281:16)
	at Socket.<anonymous> (/home/atom/.vscode/extensions/natizyskunk.sftp-1.13.5/node_modules/ssh2/lib/client.js:692:21)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote /home/atom/Documents/Work/Code/github/mainDev/src/tof.py
[07-14 11:39:31] [debug] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[07-14 11:39:31] [debug] Inbound: Received REQUEST_FAILURE
[07-14 11:40:01] [debug] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[07-14 11:40:01] [debug] Inbound: Received REQUEST_FAILURE

 - OS:  Linux
 - VSCode Version: 1.58.1
 - Extension Version : 1.13.5

**Comment by Natizyskunk** [comment]
Have you correctly configured your sftp.json config file ?

In the LOGs you gave me, it seems that you haven't defined your username and password as it show `Client: none auth failed` and `"username":"","password":""`.

Can you verify that there are actually defined ?

Also could you try this and see if you still have the error :
1. Uninstall extension from vscode.
2. Close vscode and go to `C:/Users/<username>/.vscode/extensions`. 
3. In here remove all references to the SFTP extension. Liximomo's one and Natizyskunk's one.
4. Re-open vscode and install latest version from the marketplace.

Please give me some feedbacks 🙂

**Comment by jenish-rudani** [comment]
Hi, So

I followed step 1 initially but It did not work.

However, after looking at your step 3, I checked .vscode dir on my machine and indeed there were two copies of the same SFTP available.
1. Natizyskunk's 
2. Liximomo's 

So, I removed both dir from .vscode/extensions and then installed yours again freshly.

It worked wonderfully, Thanks. My issue is resolved now.

**Comment by Natizyskunk** [comment]
I'm happy to hear that 😀

**Comment by nicojmb** [comment]
Hi, 

I've the same problema but deleting both directorys not work


`[08-26 12:46:37] [info] config at xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx {"remotePath":"xxxxxxxxxxxxxxxxxxxxxxxx","uploadOnSave":true,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[".vscode",".git",".DS_Store","README.md","test","LICENSE","license.txt"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"Production","host":"xxxxxxx","port":22,"username":"******","password":"******","syncOption":{"delete":true,"overwrite":true}}`

```
[08-26 12:47:36] [info] [file-save] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[08-26 12:47:36] [trace] handle upload file for xxxxxxxxxxxxxxxxxxxxxxxxxx
[08-26 12:47:36] [debug] Custom crypto binding not available
[08-26 12:47:36] [debug] Local ident: 'SSH-2.0-ssh2js1.5.0'
[08-26 12:47:36] [debug] Client: Trying xxxxxxxxxxxxxxxxxxxx 22 ...
[08-26 12:47:36] [debug] Socket connected
[08-26 12:47:36] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2'
[08-26 12:47:36] [debug] Outbound: Sending KEXINIT
[08-26 12:47:37] [debug] Inbound: Handshake in progress
[08-26 12:47:37] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[08-26 12:47:37] [debug] Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
[08-26 12:47:37] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[08-26 12:47:37] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[08-26 12:47:37] [debug] Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
[08-26 12:47:37] [debug] Handshake: Host key format: ssh-ed25519
[08-26 12:47:37] [debug] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[08-26 12:47:37] [debug] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[08-26 12:47:37] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[08-26 12:47:37] [debug] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[08-26 12:47:37] [debug] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[08-26 12:47:37] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[08-26 12:47:37] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-26 12:47:37] [debug] Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-26 12:47:37] [debug] Handshake: C->S MAC: <implicit>
[08-26 12:47:37] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-26 12:47:37] [debug] Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-26 12:47:37] [debug] Handshake: S->C MAC: <implicit>
[08-26 12:47:37] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[08-26 12:47:37] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[08-26 12:47:37] [debug] Handshake: C->S compression: none
[08-26 12:47:37] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[08-26 12:47:37] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[08-26 12:47:37] [debug] Handshake: S->C compression: none
[08-26 12:47:37] [debug] Outbound: Sending KEXECDH_INIT
[08-26 12:47:37] [debug] Received DH Reply
[08-26 12:47:37] [debug] Host accepted by default (no verification)
[08-26 12:47:37] [debug] Host accepted (verified)
[08-26 12:47:37] [debug] Outbound: Sending NEWKEYS
[08-26 12:47:37] [debug] Inbound: NEWKEYS
[08-26 12:47:37] [debug] Verifying signature ...
[08-26 12:47:37] [debug] Verified signature
[08-26 12:47:37] [debug] Handshake completed
[08-26 12:47:37] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[08-26 12:47:37] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[08-26 12:47:37] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[08-26 12:47:37] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[08-26 12:47:37] [debug] Client: none auth failed
[08-26 12:47:37] [debug] Outbound: Sending USERAUTH_REQUEST (password)
[08-26 12:47:37] [debug] Inbound: Received USERAUTH_SUCCESS
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[08-26 12:47:37] [debug] Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
[08-26 12:47:37] [debug] Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
[08-26 12:47:37] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[08-26 12:47:37] [debug] Inbound: REQUEST_SUCCESS
[08-26 12:47:37] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[08-26 12:47:37] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[08-26 12:47:37] [debug] Inbound: CHANNEL_DATA (r:0, 154)
[08-26 12:47:37] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com)
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_DATA (r:0, 63)
[08-26 12:47:37] [debug] SFTP: Outbound: Buffered MKDIR
[08-26 12:47:37] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-26 12:47:37] [debug] SFTP: Inbound: Received STATUS (id:0, 4, "Failure")
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_DATA (r:0, 59)
[08-26 12:47:37] [debug] SFTP: Outbound: Buffered LSTAT
[08-26 12:47:37] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[08-26 12:47:37] [debug] SFTP: Inbound: Received ATTRS (id:1)
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_DATA (r:0, 80)
[08-26 12:47:37] [debug] SFTP: Outbound: Buffered OPEN
[08-26 12:47:37] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[08-26 12:47:37] [debug] SFTP: Inbound: Received HANDLE (id:2)
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-26 12:47:37] [debug] SFTP: Outbound: Buffered FSTAT
[08-26 12:47:37] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[08-26 12:47:37] [debug] SFTP: Inbound: Received ATTRS (id:3)
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_DATA (r:0, 25)
[08-26 12:47:37] [debug] SFTP: Outbound: Buffered FSETSTAT
[08-26 12:47:37] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-26 12:47:37] [debug] SFTP: Inbound: Received STATUS (id:4, 0, "Success")
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_DATA (r:0, 686)
[08-26 12:47:37] [debug] SFTP: Outbound: Sent WRITE (id:5)
[08-26 12:47:37] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-26 12:47:37] [debug] SFTP: Inbound: Received STATUS (id:5, 4, "Failure")
[08-26 12:47:37] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-26 12:47:37] [debug] SFTP: Outbound: Buffered CLOSE
[08-26 12:47:37] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-26 12:47:37] [debug] SFTP: Inbound: Received STATUS (id:6, 0, "Success")
[08-26 12:47:37] [error] Error: Failure
    at 101 (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\SFTP.js:2618:19)
    at SFTP.push (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\SFTP.js:278:11)
    at CHANNEL_DATA (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\client.js:525:23)
    at 94 (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\handlers.misc.js:859:16)
    at Protocol.onPayload (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\Protocol.js:2025:10)
    at AESGCMDecipherNative.decrypt (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\crypto.js:987:26)
    at Protocol.parsePacket [as _parse] (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\Protocol.js:1994:25)
    at Protocol.parse (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\protocol\Protocol.js:293:16)
    at Socket.<anonymous> (c:\Users\nicojmb\.vscode\extensions\natizyskunk.sftp-1.15.14\node_modules\ssh2\lib\client.js:713:21)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) when local ➞ remote xxxxxxxxxxxxxxxxxxxxxxxxxx
```
