### ISSUE TITLE
06-09 16:22:07] [error] Error: [xx.local]: getaddrinfo EAI_AGAIN xx.local

### ISSUE THREAD

**Issue by peterlholm** [Natizyskunk/vscode-sftp#165]
**Do you read the FAQ?**
- [ X] Yes.

**Describe the bug**
Doing a upload the following error:
06-09 16:11:43] [info] config at /home/peter/danBots/sw/danbots-webserv {"remotePath":"/home/peter/danbots-webserv","uploadOnSave":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"DanWand","host":"danwand.local","username":"******","port":22,"privateKeyPath":"~/.ssh/id_rsa_danwand","profiles":{"danwand":{"host":"danwand.local","remotePath":"/home/peter/danbots-webserv"},"pizero":{"host":"192.168.0.64"},"raspberrypi":{"host":"raspberrypi.local"},"Futurebox":{"host":"10.11.131.222","username":"peter"},"cm4":{"host":"192.168.0.76","username":"peter","remotePath":"/home/peter/danbots-webserv"}},"defaultProfile":"danwand"}
[06-09 16:12:18] [info] Using profile: danwand
[06-09 16:12:53] [info] Using profile: danwand
[06-09 16:21:21] [info] Using profile: danwand
[06-09 16:21:52] [info] Using profile: danwand
[06-09 16:22:07] [info] Using profile: danwand
[06-09 16:22:07] [error] Error: [danwand.local]: getaddrinfo EAI_AGAIN danwand.local
	at Client.<anonymous> (/home/peter/.vscode/extensions/natizyskunk.sftp-1.15.14/dist/extension.js:2:242828)
	at Client.emit (node:events:402:35)
	at Socket.<anonymous> (/home/peter/.vscode/extensions/natizyskunk.sftp-1.15.14/node_modules/ssh2/lib/client.js:745:12)
	at Socket.emit (node:events:390:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[06-09 16:34:52] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[06-09 16:34:52] [debug] register command "Config" from "./commandConfig.ts"
[06-09 16:34:52] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[06-09 16:34:52] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[06-09 16:34:52] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[06-09 16:34:52] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[06-09 16:34:52] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[06-09 16:34:52] [debug] register command "Create File" from "./fileCommandCreateFile.ts"
[06-09 16:34:52] [debug] register command "Create Folder" from "./fileCommandCreateFolder.ts"
[06-09 16:34:52] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[06-09 16:34:52] [debug] register command "Diff" from "./fileCommandDiff.ts"
[06-09 16:34:52] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[06-09 16:34:52] [debug] register command "Download" from "./fileCommandDownload.ts"
[06-09 16:34:52] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[06-09 16:34:52] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[06-09 16:34:52] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[06-09 16:34:52] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[06-09 16:34:52] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[06-09 16:34:52] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[06-09 16:34:52] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[06-09 16:34:52] [debug] register command "List" from "./fileCommandList.ts"
[06-09 16:34:52] [debug] register command "List All" from "./fileCommandListAll.ts"
[06-09 16:34:52] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[06-09 16:34:52] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[06-09 16:34:52] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[06-09 16:34:52] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[06-09 16:34:52] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[06-09 16:34:52] [debug] register command "Upload" from "./fileCommandUpload.ts"
[06-09 16:34:52] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[06-09 16:34:52] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[06-09 16:34:52] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[06-09 16:34:52] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[06-09 16:34:52] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[06-09 16:34:52] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[06-09 16:34:52] [info] config at /home/peter/danBots/sw/danbots-webserv {"remotePath":"/home/peter/danbots-webserv","uploadOnSave":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"DanWand","host":"danwand.local","username":"******","port":22,"privateKeyPath":"~/.ssh/id_rsa_danwand","profiles":{"danwand":{"host":"danwand.local","remotePath":"/home/peter/danbots-webserv"},"pizero":{"host":"192.168.0.64"},"raspberrypi":{"host":"raspberrypi.local"},"Futurebox":{"host":"10.11.131.222","username":"peter"},"cm4":{"host":"192.168.0.76","username":"peter","remotePath":"/home/peter/danbots-webserv"}},"defaultProfile":"danwand"}
[06-09 16:34:58] [info] Using profile: danwand
[06-09 16:35:00] [trace] run command 'Upload File'
[06-09 16:35:00] [info] Using profile: danwand
[06-09 16:35:00] [trace] handle upload file for /home/peter/danBots/sw/danbots-webserv/webservice/test.py
[06-09 16:35:00] [debug] Custom crypto binding not available
[06-09 16:35:00] [debug] Local ident: 'SSH-2.0-ssh2js1.5.0'
[06-09 16:35:00] [debug] Client: Trying danwand.local on port 22 ...
[06-09 16:35:00] [debug] Socket error: getaddrinfo EAI_AGAIN danwand.local
[06-09 16:35:00] [error] Error: [danwand.local]: getaddrinfo EAI_AGAIN danwand.local
	at Client.<anonymous> (/home/peter/.vscode/extensions/natizyskunk.sftp-1.15.14/dist/extension.js:2:242828)
	at Client.emit (node:events:402:35)
	at Socket.<anonymous> (/home/peter/.vscode/extensions/natizyskunk.sftp-1.15.14/node_modules/ssh2/lib/client.js:745:12)
	at Socket.emit (node:events:390:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[06-09 16:35:00] [debug] Socket closed

ping danwand.local works fine

**Everything works fine on windows and ubuntu 20 **

**To Reproduce**
2. Run command 'Upload active file'
3. See error

**Expected behavior**
an upload

**Screenshots**

**Desktop (please complete the following information):**
 
Config:
SFTP v.1.15.15
vscode: 1.67.2
nodejs: 16.13.0
OS: Ubunto 22.04.LTS

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.
[06-09 16:34:52] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[06-09 16:34:52] [debug] register command "Config" from "./commandConfig.ts"
[06-09 16:34:52] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[06-09 16:34:52] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[06-09 16:34:52] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[06-09 16:34:52] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[06-09 16:34:52] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[06-09 16:34:52] [debug] register command "Create File" from "./fileCommandCreateFile.ts"
[06-09 16:34:52] [debug] register command "Create Folder" from "./fileCommandCreateFolder.ts"
[06-09 16:34:52] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[06-09 16:34:52] [debug] register command "Diff" from "./fileCommandDiff.ts"
[06-09 16:34:52] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[06-09 16:34:52] [debug] register command "Download" from "./fileCommandDownload.ts"
[06-09 16:34:52] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[06-09 16:34:52] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[06-09 16:34:52] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[06-09 16:34:52] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[06-09 16:34:52] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[06-09 16:34:52] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[06-09 16:34:52] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[06-09 16:34:52] [debug] register command "List" from "./fileCommandList.ts"
[06-09 16:34:52] [debug] register command "List All" from "./fileCommandListAll.ts"
[06-09 16:34:52] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[06-09 16:34:52] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[06-09 16:34:52] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[06-09 16:34:52] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[06-09 16:34:52] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[06-09 16:34:52] [debug] register command "Upload" from "./fileCommandUpload.ts"
[06-09 16:34:52] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[06-09 16:34:52] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[06-09 16:34:52] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[06-09 16:34:52] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[06-09 16:34:52] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[06-09 16:34:52] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[06-09 16:34:52] [info] config at /home/peter/danBots/sw/danbots-webserv {"remotePath":"/home/peter/danbots-webserv","uploadOnSave":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"DanWand","host":"danwand.local","username":"******","port":22,"privateKeyPath":"~/.ssh/id_rsa_danwand","profiles":{"danwand":{"host":"danwand.local","remotePath":"/home/peter/danbots-webserv"},"pizero":{"host":"192.168.0.64"},"raspberrypi":{"host":"raspberrypi.local"},"Futurebox":{"host":"10.11.131.222","username":"peter"},"cm4":{"host":"192.168.0.76","username":"peter","remotePath":"/home/peter/danbots-webserv"}},"defaultProfile":"danwand"}
[06-09 16:34:58] [info] Using profile: danwand
[06-09 16:35:00] [trace] run command 'Upload File'
[06-09 16:35:00] [info] Using profile: danwand
[06-09 16:35:00] [trace] handle upload file for /home/peter/danBots/sw/danbots-webserv/webservice/test.py
[06-09 16:35:00] [debug] Custom crypto binding not available
[06-09 16:35:00] [debug] Local ident: 'SSH-2.0-ssh2js1.5.0'
[06-09 16:35:00] [debug] Client: Trying danwand.local on port 22 ...
[06-09 16:35:00] [debug] Socket error: getaddrinfo EAI_AGAIN danwand.local
[06-09 16:35:00] [error] Error: [danwand.local]: getaddrinfo EAI_AGAIN danwand.local
	at Client.<anonymous> (/home/peter/.vscode/extensions/natizyskunk.sftp-1.15.14/dist/extension.js:2:242828)
	at Client.emit (node:events:402:35)
	at Socket.<anonymous> (/home/peter/.vscode/extensions/natizyskunk.sftp-1.15.14/node_modules/ssh2/lib/client.js:745:12)
	at Socket.emit (node:events:390:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[06-09 16:35:00] [debug] Socket closed

**Comment by Moln** [comment]
The plugin will load file ` ~/.ssh/config`  and resolve `HostName` option.
Confirm your have `HostName: xx.local` option in that file.

If found it, try delete that option or delete `~/.ssh/config` file.
