### ISSUE TITLE
Can't write comments in the sftp.json configuration file

### ISSUE THREAD

**Issue by fazaldegui** [Natizyskunk/vscode-sftp#191]
**Do you read the FAQ?**
- [x] Yes.
- [x] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Can't write comments in the sftp.json configuration file.
The file stored in .vscode folder called "sftp.json" contains the server information, if I write a comment on saving the json file an error of "Unexpected token in position X" is thrown.
In the output panel this is shown:
```
[09-14 08:08:44] [error] SyntaxError: c:\Datos\Proyectos\Sw\Cosmos\CS.DG.516\.vscode\sftp.json: Unexpected token / in JSON at position 61
	at JSON.parse (<anonymous>)
	at c:\Users\Fernando\.vscode\extensions\natizyskunk.sftp-1.15.14\dist\extension.js:2:147271
	at c:\Users\Fernando\.vscode\extensions\natizyskunk.sftp-1.15.14\dist\extension.js:2:41030
	at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
``` 

**To Reproduce**
1. Open the sftp.json file: Ctrl+Sht+P  and the command "SFTP: Config"
2. The json file is open.
3. Write a server information with a comment, for ex: 
```
{
   "name": "VM_Alpine",
   "host": "192.168.56.105",
   // test comment
   "protocol": "sftp",
   "port": 22,
   "username": "holst",
   "remotePath": "/home/holst/sw/Cosmos/CS.DG.516",
   "uploadOnSave": true,
   "useTempFile": false,
   "openSsh": false,
   "ignore": [
      ".vscode",
      ".git",
      ".DS_Store"
   ]
}
```
4. Ctrl+S to save the file
5. The error for parsing the file is shown:
```
[09-14 08:16:03] [error] SyntaxError: c:\Datos\Proyectos\Sw\Cosmos\CS.DG.516\.vscode\sftp.json: Unexpected token / in JSON at position 61
	at JSON.parse (<anonymous>)
	at c:\Users\Fernando\.vscode\extensions\natizyskunk.sftp-1.15.14\dist\extension.js:2:147271
	at c:\Users\Fernando\.vscode\extensions\natizyskunk.sftp-1.15.14\dist\extension.js:2:41030
	at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) 
```

**Expected behavior**
Write comment in the json file to be legal

**Desktop (please complete the following information):**
 - OS: Win
 - VSCode Version 1.71.1
 - Extension Version 1.15.14

**Extension Logs from Startup** - *required*
```
[09-14 08:20:49] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[09-14 08:20:49] [debug] register command "Config" from "./commandConfig.ts"
[09-14 08:20:49] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[09-14 08:20:49] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[09-14 08:20:49] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[09-14 08:20:49] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[09-14 08:20:49] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[09-14 08:20:49] [debug] register command "Create File" from "./fileCommandCreateFile.ts"
[09-14 08:20:49] [debug] register command "Create Folder" from "./fileCommandCreateFolder.ts"
[09-14 08:20:49] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[09-14 08:20:49] [debug] register command "Diff" from "./fileCommandDiff.ts"
[09-14 08:20:49] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[09-14 08:20:49] [debug] register command "Download" from "./fileCommandDownload.ts"
[09-14 08:20:49] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[09-14 08:20:49] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[09-14 08:20:49] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[09-14 08:20:49] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[09-14 08:20:49] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[09-14 08:20:49] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[09-14 08:20:49] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[09-14 08:20:49] [debug] register command "List" from "./fileCommandList.ts"
[09-14 08:20:49] [debug] register command "List All" from "./fileCommandListAll.ts"
[09-14 08:20:49] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[09-14 08:20:49] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[09-14 08:20:49] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[09-14 08:20:49] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[09-14 08:20:49] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[09-14 08:20:49] [debug] register command "Upload" from "./fileCommandUpload.ts"
[09-14 08:20:49] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[09-14 08:20:49] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[09-14 08:20:49] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[09-14 08:20:49] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[09-14 08:20:49] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[09-14 08:20:49] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[09-14 08:20:50] [error] SyntaxError: c:\Datos\Proyectos\Sw\Cosmos\CS.DG.516\.vscode\sftp.json: Unexpected token / in JSON at position 61
	at JSON.parse (<anonymous>)
	at c:\Users\Fernando\.vscode\extensions\natizyskunk.sftp-1.15.14\dist\extension.js:2:147271
	at c:\Users\Fernando\.vscode\extensions\natizyskunk.sftp-1.15.14\dist\extension.js:2:41030
	at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) 
[09-14 08:21:07] [error] SyntaxError: c:\Datos\Proyectos\Sw\Cosmos\CS.DG.516\.vscode\sftp.json: Unexpected token / in JSON at position 61
	at JSON.parse (<anonymous>)
	at c:\Users\Fernando\.vscode\extensions\natizyskunk.sftp-1.15.14\dist\extension.js:2:147271
	at c:\Users\Fernando\.vscode\extensions\natizyskunk.sftp-1.15.14\dist\extension.js:2:41030
	at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) 
```

**Comment by MisterFixx** [comment]
Comments are not supported in JSON.

**Comment by fazaldegui** [comment]
Sorry, you're right.
I've seen in your examples comments and I'm assumed that it could be.
Thank you.
