### ISSUE TITLE
Timed out while waiting for handshake

### ISSUE THREAD

**Issue by Mickeywaugh** [Natizyskunk/vscode-sftp#20]
[07-19 13:05:42] [debug] Custom crypto binding not available
[07-19 13:05:42] [debug] Client: Trying 172.24.202.215 on port 22 ...
[07-19 13:05:42] [debug] Local ident: 'SSH-2.0-ssh2js1.1.0'
[07-19 13:05:42] [debug] Socket connected
[07-19 13:05:42] [debug] Remote ident: 'SSH-2.0-OpenSSH_5.3'
[07-19 13:05:42] [debug] Outbound: Sending KEXINIT
[07-19 13:05:42] [debug] Inbound: Handshake in progress
[07-19 13:05:42] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[07-19 13:05:42] [debug] Handshake: (remote) KEX method: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[07-19 13:05:42] [debug] Handshake: KEX algorithm: diffie-hellman-group-exchange-sha256
[07-19 13:05:42] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[07-19 13:05:42] [debug] Handshake: (remote) Host key format: ssh-rsa,ssh-dss
[07-19 13:05:42] [debug] Handshake: Host key format: ssh-rsa
[07-19 13:05:42] [debug] Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[07-19 13:05:42] [debug] Handshake: (remote) C->S cipher: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[07-19 13:05:42] [debug] Handshake: C->S Cipher: aes128-ctr
[07-19 13:05:42] [debug] Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[07-19 13:05:42] [debug] Handshake: (remote) S->C cipher: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
[07-19 13:05:42] [debug] Handshake: S->C cipher: aes128-ctr
[07-19 13:05:42] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-19 13:05:42] [debug] Handshake: (remote) C->S MAC: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[07-19 13:05:42] [debug] Handshake: C->S MAC: hmac-sha2-256
[07-19 13:05:42] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[07-19 13:05:42] [debug] Handshake: (remote) S->C MAC: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
[07-19 13:05:42] [debug] Handshake: S->C MAC: hmac-sha2-256
[07-19 13:05:42] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[07-19 13:05:42] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[07-19 13:05:42] [debug] Handshake: C->S compression: none
[07-19 13:05:42] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[07-19 13:05:42] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[07-19 13:05:42] [debug] Handshake: S->C compression: none
[07-19 13:05:42] [debug] Outbound: Sending KEXDH_GEX_REQUEST
[07-19 13:05:42] [debug] Received DH GEX Group
[07-19 13:06:03] [debug] Outbound: Sending KEXDH_GEX_INIT
[07-19 13:06:03] [debug] Outbound: Sending DISCONNECT (11)
[07-19 13:06:03] [error] Error: [172.24.202.215]: Timed out while waiting for handshake
	at Client.<anonymous> (c:\Users\Mickeywaugh\.vscode\extensions\natizyskunk.sftp-1.13.6\dist\extension.js:61:99994)
	at Client.emit (events.js:327:22)
	at Timeout._onTimeout (c:\Users\Mickeywaugh\.vscode\extensions\natizyskunk.sftp-1.13.6\node_modules\ssh2\lib\client.js:995:16)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7) 
[07-19 13:06:03] [debug] Socket closed

**Comment by fabrazer** [comment]
I got the same issue. Also tested it with v1.14.0-beta -> same issue.

**Comment by Natizyskunk** [comment]
Check the connection of your server.  Also try a larger connectTimeout value.
I personnaly use `"connectTimeout": 1800000`.

**Comment by fabrazer** [comment]
Increased connect timeout works for me. Thank you!

**Comment by Natizyskunk** [comment]
Cool, no problem :)

**Comment by fabrazer** [comment]
Maybe you can also increase the default connectTmeout to 1800000?  :)

**Comment by Mickeywaugh** [comment]
I switched to version 1.12.9 , it works normal.

**Comment by Mickeywaugh** [comment]
My sftp.json  structure as below:
`[
    {
        "name": "composite",
        "context": "composite/",
        "protocol": "sftp",
        "port": 22,
        "username": "root",
        "password": "password",
        "remotePath": "/",
        "uploadOnSave": true,
        "passive": true,
        "ignore": [
            ".vscode",
            ".idea",
            ".DS_Store"
        ],
        "profiles": {
            "212": {
                "host": "172.24.202.212"
            },
            "213": {
                "host": "172.24.202.213"
            },
            "215": {
                "host": "172.24.202.215"
            },
            "216": {
                "host": "172.24.202.216"
            }
        }
    },
    {
        "name": "i18n",
        "context": "i18n/",
        "protocol": "sftp",
        "port": 22,
        "username": "root",
        "password": "password",
        "remotePath": "/root/i18n",
        "uploadOnSave": true,
        "passive": true,
        "ignore": [
            ".vscode",
            ".idea",
            ".DS_Store"
        ],
        "profiles": {
            "212": {
                "host": "172.24.202.212"
            },
            "213": {
                "host": "172.24.202.213"
            },
            "215": {
                "host": "172.24.202.215"
            },
            "216": {
                "host": "172.24.202.216"
            }
        },
        "defaultProfile": "215"
    }
]`

**Comment by Mickeywaugh** [comment]
I tried to set "connectTmeout=180000", it not works,logs asbelow:
``
[07-20 09:22:03] [debug] Handshake: S->C compression: none
[07-20 09:22:03] [debug] Outbound: Sending KEXDH_GEX_REQUEST
[07-20 09:22:03] [debug] Received DH GEX Group
[07-20 09:22:25] [debug] Outbound: Sending KEXDH_GEX_INIT
[07-20 09:22:25] [debug] Received DH GEX Reply
[07-20 09:22:25] [debug] Received DH Reply
[07-20 09:22:25] [debug] Host accepted by default (no verification)
[07-20 09:22:25] [debug] Host accepted (verified)
[07-20 09:22:25] [debug] Inbound: NEWKEYS
[07-20 09:22:25] [debug] Verifying signature ...
[07-20 09:22:25] [debug] Verified signature
[07-20 09:22:25] [debug] Outbound: Sending NEWKEYS
[07-20 09:22:25] [debug] Handshake completed
[07-20 09:22:25] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[07-20 09:22:25] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[07-20 09:22:25] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[07-20 09:22:25] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[07-20 09:22:25] [debug] Client: none auth failed
[07-20 09:22:25] [debug] Outbound: Sending USERAUTH_REQUEST (password)
[07-20 09:22:27] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[07-20 09:22:27] [debug] Client: password auth failed
[07-20 09:22:27] [debug] Outbound: Sending DISCONNECT (11)
[07-20 09:22:27] [debug] Socket ended
[07-20 09:22:27] [debug] Socket closed
[07-20 09:26:11] [trace] run command 'Toggle Output Panel'
``

the log shows it may be authorization failed. 
Actually I reinstall the VM with same version OS, and set the username and  password as before.

**Comment by Mickeywaugh** [comment]
OK， I got the root cause, It's my fault.

**Comment by fabrazer** [comment]
@Mickeywaugh what caused the timeout in your case?

**Comment by Mickeywaugh** [comment]
> @Mickeywaugh what caused the timeout in your case?

password changed in sftp.json....
