### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by junfengshow** [Natizyskunk/vscode-sftp#28]
Error: [116.62.145.208]: All configured authentication methods failed
	at Client.<anonymous> (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\dist\extension.js:61:100690)
	at Client.emit (events.js:327:22)
	at doNextAuth (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\client.js:784:14)
	at tryNextAuth (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\client.js:972:7)
	at USERAUTH_FAILURE (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\client.js:367:11)
	at 51 (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\protocol\handlers.misc.js:333:16)
	at Protocol.onPayload (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\protocol\Protocol.js:1974:10)
	at AESGCMDecipherNative.decrypt (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\protocol\crypto.js:992:26)
	at Protocol.parsePacket [as _parse] (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\protocol\Protocol.js:1943:25)
	at Protocol.parse (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\protocol\Protocol.js:281:16)
	at Socket.<anonymous> (c:\Users\Admin\.vscode\extensions\natizyskunk.sftp-1.14.0\node_modules\ssh2\lib\client.js:692:21)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by Natizyskunk** [comment]
FAQ : https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md#error-connection-closed

The problem would be that the SFTP extension keeps closing the connection for those who use more legacy/old systems. You'll have to Explicitly override the default transport layer algorithms used for the connection to remove the new "diffie-hellman-group-exchange-sha256" algorithm that cause the problem from the kex section. Just add this in your sftp.json config file, which should make it work.
```json
{
	...
	"host": "exemple.com",
	...
	"algorithms": {
		"kex": [
			"ecdh-sha2-nistp256", 
			"ecdh-sha2-nistp384", 
			"ecdh-sha2-nistp521", 
			"diffie-hellman-group14-sha1"
		],
		"cipher": [
			"aes128-ctr", 
			"aes192-ctr", 
			"aes256-ctr", 
			"aes128-gcm", 
			"aes128-gcm@openssh.com", 
			"aes256-gcm", 
			"aes256-gcm@openssh.com"
		],
		"serverHostKey": [
			"ssh-rsa", 
			"ecdsa-sha2-nistp256", 
			"ecdsa-sha2-nistp384", 
			"ecdsa-sha2-nistp521"
		],
		"hmac": [
			"hmac-sha2-256", 
			"hmac-sha2-512", 
			"hmac-sha1"
		]
	}
}
```


**References:** 
_Originally posted by @montorodiaz in https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-783402096_
https://github.com/liximomo/vscode-sftp/wiki/SFTP-only-Config#sshcustomparams

**Comment by kalvinchang** [comment]
This does not fix the issue for me

**Comment by Natizyskunk** [comment]
Can you please be more precise on when do you get this error ?
If you have no password and no ssh key configured, of course all configured authentication methods would fail.

If you've to specified the password in you' sftp.json config file, maybe it mean that there is a proble with your server configuration. Maybe it only accept password authentication method, and you'll have to enable SSH on it to make it work.

Please edit your issue and use the `bug_report` issue template available [here](https://github.com/Natizyskunk/vscode-sftp/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Thanks.

**Comment by kalvinchang** [comment]
Deleting ~/.ssh on my local computer fixed the issue. I now get prompted every time to enter my password, which is what i want to happen.
