### ISSUE TITLE
Upload Active File Fails

### ISSUE THREAD

**Issue by dapatil211** [Natizyskunk/vscode-sftp#311]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Upload Active File fails with `Error: Failure`. In the FAQ, it says to try setting `limitOpenFilesOnRemote` to true. When I do that, I get `TypeError: Cannot read properties of undefined (reading 'open')`

**To Reproduce**
1. Try Running "Upload active file"

**Expected behavior**
The file is uploaded to the remote server. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCode Version 1.75.1
 - Extension Version 1.16.1

**Extension Logs from Startup** - *required*
```
[02-13 17:28:23] [info] [file-save] **file_name**
[02-13 17:28:23] [trace] handle upload file for **file_name**
[02-13 17:28:23] [debug] Custom crypto binding not available
[02-13 17:28:23] [debug] Local ident: 'SSH-2.0-ssh2js1.11.0'
[02-13 17:28:23] [debug] Client: Trying **hostname** on port 2222 ...
[02-13 17:28:23] [debug] Socket connected
[02-13 17:28:23] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5'
[02-13 17:28:23] [debug] Outbound: Sending KEXINIT
[02-13 17:28:23] [debug] Inbound: Handshake in progress
[02-13 17:28:23] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[02-13 17:28:23] [debug] Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
[02-13 17:28:23] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[02-13 17:28:23] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[02-13 17:28:23] [debug] Handshake: (remote) Host key format: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[02-13 17:28:23] [debug] Handshake: Host key format: ssh-ed25519
[02-13 17:28:23] [debug] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[02-13 17:28:23] [debug] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[02-13 17:28:23] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[02-13 17:28:23] [debug] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[02-13 17:28:23] [debug] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[02-13 17:28:23] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[02-13 17:28:23] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[02-13 17:28:23] [debug] Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[02-13 17:28:23] [debug] Handshake: C->S MAC: <implicit>
[02-13 17:28:23] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[02-13 17:28:23] [debug] Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[02-13 17:28:23] [debug] Handshake: S->C MAC: <implicit>
[02-13 17:28:23] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[02-13 17:28:23] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[02-13 17:28:23] [debug] Handshake: C->S compression: none
[02-13 17:28:23] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[02-13 17:28:23] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[02-13 17:28:23] [debug] Handshake: S->C compression: none
[02-13 17:28:23] [debug] Outbound: Sending KEXECDH_INIT
[02-13 17:28:23] [debug] Received DH Reply
[02-13 17:28:23] [debug] Host accepted by default (no verification)
[02-13 17:28:23] [debug] Host accepted (verified)
[02-13 17:28:23] [debug] Outbound: Sending NEWKEYS
[02-13 17:28:23] [debug] Inbound: NEWKEYS
[02-13 17:28:23] [debug] Verifying signature ...
[02-13 17:28:23] [debug] Verified signature
[02-13 17:28:23] [debug] Handshake completed
[02-13 17:28:23] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[02-13 17:28:23] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[02-13 17:28:23] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[02-13 17:28:23] [debug] Inbound: Received USERAUTH_FAILURE (publickey,keyboard-interactive)
[02-13 17:28:23] [debug] Client: none auth failed
[02-13 17:28:23] [debug] Agent: Trying key #1
[02-13 17:28:23] [debug] Outbound: Sending USERAUTH_REQUEST (publickey -- check)
[02-13 17:28:23] [debug] Inbound: Received USERAUTH_PK_OK
[02-13 17:28:23] [debug] Outbound: Sending USERAUTH_REQUEST (publickey)
[02-13 17:28:23] [debug] Inbound: Received USERAUTH_SUCCESS
[02-13 17:28:23] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[02-13 17:28:24] [debug] Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
[02-13 17:28:24] [debug] Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
[02-13 17:28:24] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[02-13 17:28:24] [debug] Inbound: REQUEST_SUCCESS
[02-13 17:28:24] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[02-13 17:28:24] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 154)
[02-13 17:28:24] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com)
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 98)
[02-13 17:28:24] [debug] SFTP: Outbound: Buffered MKDIR
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[02-13 17:28:24] [debug] SFTP: Inbound: Received STATUS (id:0, 4, "Failure")
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 94)
[02-13 17:28:24] [debug] SFTP: Outbound: Buffered LSTAT
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[02-13 17:28:24] [debug] SFTP: Inbound: Received ATTRS (id:1)
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 113)
[02-13 17:28:24] [debug] SFTP: Outbound: Buffered OPEN
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[02-13 17:28:24] [debug] SFTP: Inbound: Received HANDLE (id:2)
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[02-13 17:28:24] [debug] SFTP: Outbound: Buffered FSTAT
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[02-13 17:28:24] [debug] SFTP: Inbound: Received ATTRS (id:3)
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 25)
[02-13 17:28:24] [debug] SFTP: Outbound: Buffered FSETSTAT
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[02-13 17:28:24] [debug] SFTP: Inbound: Received STATUS (id:4, 0, "Success")
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 3700)
[02-13 17:28:24] [debug] SFTP: Outbound: Sent WRITE (id:5)
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[02-13 17:28:24] [debug] SFTP: Inbound: Received STATUS (id:5, 0, "Success")
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 29)
[02-13 17:28:24] [debug] SFTP: Outbound: Buffered FSETSTAT
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[02-13 17:28:24] [debug] SFTP: Inbound: Received STATUS (id:6, 0, "Success")
[02-13 17:28:24] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[02-13 17:28:24] [debug] SFTP: Outbound: Buffered CLOSE
[02-13 17:28:24] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[02-13 17:28:24] [debug] SFTP: Inbound: Received STATUS (id:7, 4, "Failure")
[02-13 17:28:24] [error] Error: Failure
	at 101 (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/SFTP.js:2704:19)
	at SFTP.push (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/SFTP.js:278:11)
	at CHANNEL_DATA (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/client.js:525:23)
	at 94 (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/handlers.misc.js:859:16)
	at Protocol.onPayload (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
	at AESGCMDecipherNative.decrypt (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/crypto.js:987:26)
	at Protocol.parsePacket [as _parse] (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
	at Protocol.parse (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
	at Socket.<anonymous> (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/client.js:713:21)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23) when local ➞ remote **file_name**
```

Logs from setting `limitOpenFilesOnRemote` to true:
```
[02-13 17:37:59] [info] [file-save] **file_name**
[02-13 17:37:59] [trace] handle upload file for **file_name**
[02-13 17:37:59] [debug] Custom crypto binding not available
[02-13 17:37:59] [debug] Local ident: 'SSH-2.0-ssh2js1.11.0'
[02-13 17:37:59] [debug] Client: Trying **hostname** on port 2222 ...
[02-13 17:37:59] [debug] Socket connected
[02-13 17:37:59] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5'
[02-13 17:37:59] [debug] Outbound: Sending KEXINIT
[02-13 17:37:59] [debug] Inbound: Handshake in progress
[02-13 17:37:59] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[02-13 17:37:59] [debug] Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
[02-13 17:37:59] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[02-13 17:37:59] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[02-13 17:37:59] [debug] Handshake: (remote) Host key format: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[02-13 17:37:59] [debug] Handshake: Host key format: ssh-ed25519
[02-13 17:37:59] [debug] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[02-13 17:37:59] [debug] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[02-13 17:37:59] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[02-13 17:37:59] [debug] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[02-13 17:37:59] [debug] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[02-13 17:37:59] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[02-13 17:37:59] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[02-13 17:37:59] [debug] Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[02-13 17:37:59] [debug] Handshake: C->S MAC: <implicit>
[02-13 17:37:59] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[02-13 17:37:59] [debug] Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[02-13 17:37:59] [debug] Handshake: S->C MAC: <implicit>
[02-13 17:37:59] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[02-13 17:37:59] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[02-13 17:37:59] [debug] Handshake: C->S compression: none
[02-13 17:37:59] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[02-13 17:37:59] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[02-13 17:37:59] [debug] Handshake: S->C compression: none
[02-13 17:37:59] [debug] Outbound: Sending KEXECDH_INIT
[02-13 17:37:59] [debug] Received DH Reply
[02-13 17:37:59] [debug] Host accepted by default (no verification)
[02-13 17:37:59] [debug] Host accepted (verified)
[02-13 17:37:59] [debug] Outbound: Sending NEWKEYS
[02-13 17:37:59] [debug] Inbound: NEWKEYS
[02-13 17:37:59] [debug] Verifying signature ...
[02-13 17:37:59] [debug] Verified signature
[02-13 17:37:59] [debug] Handshake completed
[02-13 17:37:59] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[02-13 17:37:59] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[02-13 17:37:59] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[02-13 17:37:59] [debug] Inbound: Received USERAUTH_FAILURE (publickey,keyboard-interactive)
[02-13 17:37:59] [debug] Client: none auth failed
[02-13 17:37:59] [debug] Agent: Trying key #1
[02-13 17:37:59] [debug] Outbound: Sending USERAUTH_REQUEST (publickey -- check)
[02-13 17:37:59] [debug] Inbound: Received USERAUTH_PK_OK
[02-13 17:37:59] [debug] Outbound: Sending USERAUTH_REQUEST (publickey)
[02-13 17:38:04] [debug] Inbound: Received USERAUTH_SUCCESS
[02-13 17:38:04] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[02-13 17:38:09] [debug] Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
[02-13 17:38:09] [debug] Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
[02-13 17:38:09] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[02-13 17:38:09] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[02-13 17:38:09] [debug] Inbound: REQUEST_SUCCESS
[02-13 17:38:09] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[02-13 17:38:09] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[02-13 17:38:09] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[02-13 17:38:09] [debug] Inbound: CHANNEL_DATA (r:0, 154)
[02-13 17:38:09] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com)
[02-13 17:38:09] [debug] Outbound: Sending DISCONNECT (11)
[02-13 17:38:09] [error] TypeError: Cannot read properties of undefined (reading 'open')
	at d._limitSftpFileDescriptor (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/dist/extension.js:2:278326)
	at d.<anonymous> (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/dist/extension.js:2:278165)
	at Generator.next (<anonymous>)
	at s (/Users/darshanpatil/.vscode/extensions/natizyskunk.sftp-1.16.1/dist/extension.js:2:276026)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) download **file_name**
[02-13 17:38:09] [debug] Socket ended
[02-13 17:38:09] [debug] Socket closed
```

**Comment by lapega** [comment]
Same problem here (also on macOS)
