### ISSUE TITLE
Error: "No Available Profile" when "uploadOnSave" is set to true in .vscode/sftp.json

### ISSUE THREAD

**Issue by evtimov** [Natizyskunk/vscode-sftp#339]
```
SFTP - Pre-release
v1.16.2
-----
Version: 1.77.1 (user setup)
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:21:11.906Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

Thank you for this great extension!

If you don't mind, I would like to report a small bug (using Windows 10) which prevents "uploadOnSave": true in .vscode/sftp.json to work as expected.

CTRL+S saves the file but it doesn't actually upload it.

Instead the extension produces following error:

`[error] Error: Config Not Found.`

This is my .vscode/sftp.json file:
Remote explorer works just fine, I am able to manually browse, upload and download files.

```
{
    "name": "My Project",
    "host": "192.168.1.140",
    "protocol": "ftp",
    "port": 21,
    "username": "ftpusers",
    "password": "ftppassword",
    "remotePath": "public_html/",
    "uploadOnSave": true
}
```

**PLEASE NOTE THAT THIS PROBLEM OCCURS ONLY in SFTP - Pre-release v1.16.2, EVERYTHING WORKS FINE IN  v1.16.1.**

Here is the log output:

```
[04-09 21:39:00] [info] [file-save] E:\_GIT\Project\TODO.txt
[04-09 21:39:00] [error] Error: Config Not Found. (file:///e:/_GIT/Project/TODO.txt)
	at l (c:\Users\User\.vscode\extensions\natizyskunk.sftp-1.16.2\dist\extension.js:2:292558)
	at Object.<anonymous> (c:\Users\User\.vscode\extensions\natizyskunk.sftp-1.16.2\dist\extension.js:2:292922)
	at Generator.next (<anonymous>)
	at c:\Users\User\.vscode\extensions\natizyskunk.sftp-1.16.2\dist\extension.js:2:292298
	at new Promise (<anonymous>)
	at n (c:\Users\User\.vscode\extensions\natizyskunk.sftp-1.16.2\dist\extension.js:2:292043)
	at Object.<anonymous> (c:\Users\User\.vscode\extensions\natizyskunk.sftp-1.16.2\dist\extension.js:2:292861)
	at c:\Users\User\.vscode\extensions\natizyskunk.sftp-1.16.2\dist\extension.js:2:319157
	at Generator.next (<anonymous>)
	at s (c:\Users\User\.vscode\extensions\natizyskunk.sftp-1.16.2\dist\extension.js:2:318200) download E:\_GIT\Project\TODO.txt
```

**Comment by evtimov** [comment]
I have managed to replicate this issue @Natizyskunk 

I use a small Windows tool called "**Visual Subst**", which is basically a tool that allows you to associate a local directory with a virtual drive (drive letter). I suppose similar if not the same as mapped network drives. 

To summarize, working from a **_local folder_** `e:\\work\\project1` is fine but if I start working from a **_local virtual drive_** `v:\\work\\project1\`  then the issue appears as described above.

Can you think of a fix please?
