### ISSUE TITLE
"uploadOnSave" No Longer Works Since Today's Update

### ISSUE THREAD

**Issue by rigiddesign** [Natizyskunk/vscode-sftp#363]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When saving any file, it is no longer uploading when "uploadOnSave" is set to true

**To Reproduce**
1. Set "uploadOnSave" to true in a config file
2. Save a file
3. You will see it does not upload

**Expected behavior**
File to be uploaded

**Extension Logs from Startup** - *required*

[06-16 14:07:38] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[06-16 14:07:38] [debug] register command "Config" from "./commandConfig.ts"
[06-16 14:07:38] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[06-16 14:07:38] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[06-16 14:07:38] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[06-16 14:07:38] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[06-16 14:07:38] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[06-16 14:07:38] [debug] register command "Create File" from "./fileCommandCreateFile.ts"
[06-16 14:07:38] [debug] register command "Create Folder" from "./fileCommandCreateFolder.ts"
[06-16 14:07:38] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[06-16 14:07:38] [debug] register command "Diff" from "./fileCommandDiff.ts"
[06-16 14:07:38] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[06-16 14:07:38] [debug] register command "Download" from "./fileCommandDownload.ts"
[06-16 14:07:38] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[06-16 14:07:38] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[06-16 14:07:38] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[06-16 14:07:38] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[06-16 14:07:38] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[06-16 14:07:38] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[06-16 14:07:38] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[06-16 14:07:38] [debug] register command "List" from "./fileCommandList.ts"
[06-16 14:07:38] [debug] register command "List All" from "./fileCommandListAll.ts"
[06-16 14:07:38] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[06-16 14:07:38] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[06-16 14:07:38] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[06-16 14:07:38] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[06-16 14:07:38] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[06-16 14:07:38] [debug] register command "Upload" from "./fileCommandUpload.ts"
[06-16 14:07:38] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[06-16 14:07:38] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[06-16 14:07:38] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[06-16 14:07:38] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[06-16 14:07:38] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[06-16 14:07:38] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[06-16 14:07:38] [debug] register command "Upload Active File To All Profiles" from "./fileMultiCommandUploadActiveFileToAllProfiles.ts"
[06-16 14:07:38] [debug] register command "Upload Active Folder To All Profiles" from "./fileMultiCommandUploadActiveFolderToAllProfiles.ts"
[06-16 14:07:38] [debug] register command "Upload File To All Profiles" from "./fileMultiCommandUploadFileToAllProfiles.ts"
[06-16 14:07:38] [debug] register command "Upload Folder To All Profiles" from "./fileMultiCommandUploadFolderToAllProfiles.ts"
[06-16 14:07:38] [debug] register command "Upload Force To All Profiles" from "./fileMultiCommandUploadForceToAllProfiles.ts"
[06-16 14:07:38] [debug] register command "Upload Project To All Profiles" from "./fileMultiCommandUploadProjectToAllProfiles.ts"
[06-16 14:07:38] [debug] register command "Upload To All Profiles" from "./fileMultiCommandUploadToAllProfiles.ts"
[06-16 14:07:38] [info] config at w:\Source\Staff {"remotePath":"/home/staff/public_html/","uploadOnSave":true,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"remoteExplorer":{"order":0},"host":"om.getyouonline.co.uk","port":2244,"username":"******","privateKeyPath":"C:\\Users\\kingr\\OneDrive - Rigid Software Design Ltd\\Synced\\TimMaiden-GYOL.ppk"}
[06-16 14:07:39] [warn] ENOENT: no such file or directory, open 'USER_DIR_HERE \.ssh\config' load USER_DIR_HERE \.ssh\config failed
[06-16 14:07:44] [info] [file-save] PROJECT_PATH
[06-16 14:07:44] [error] Error: Config Not Found. (PROJECT_PATH/pages/notifications/server.php)
    at l (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296202)
    at Object.<anonymous> (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296960)
    at Generator.next (<anonymous>)
    at USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295920
    at new Promise (<anonymous>)
    at n (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295665)
    at Object.<anonymous> (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296899)
    at USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:324013
    at Generator.next (<anonymous>)
    at s (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:323056) download PROJECT_PATH
[06-16 14:07:47] [info] [file-save] PROJECT_PATH
[06-16 14:07:47] [error] Error: Config Not Found. (file://localhost/C$/Users/kingr/OneDrive - Getyouonline.co.uk Ltd/Source/Staff/pages/notifications/server.php)
    at l (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296202)
    at Object.<anonymous> (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296960)
    at Generator.next (<anonymous>)
    at USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295920
    at new Promise (<anonymous>)
    at n (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295665)
    at Object.<anonymous> (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296899)
    at USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:324013
    at Generator.next (<anonymous>)
    at s (USER_DIR_HERE \.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:323056) download PROJECT_PATH

**Comment by FlipZoomMedia** [comment]
Same here.

```
[06-16 16:39:27] [info] [file-save] \\PATH\FILE.XXXX
[06-16 16:39:27] [error] Error: Config Not Found. (file://PATH/FILE.XXXX)
    at l (c:\Users\FZM-DESKTOP.FZM-DESKTOP\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296202)
    at Object.<anonymous> (c:\Users\FZM-DESKTOP.FZM-DESKTOP\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296960)
    at Generator.next (<anonymous>)
    at c:\Users\FZM-DESKTOP.FZM-DESKTOP\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295920
    at new Promise (<anonymous>)
    at n (c:\Users\FZM-DESKTOP.FZM-DESKTOP\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295665)
    at Object.<anonymous> (c:\Users\FZM-DESKTOP.FZM-DESKTOP\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296899)
    at c:\Users\FZM-DESKTOP.FZM-DESKTOP\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:324013
    at Generator.next (<anonymous>)
    at s (c:\Users\FZM-DESKTOP.FZM-DESKTOP\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:323056)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) download \\PATH\FILE.XXXX

**Comment by dsanmartin** [comment]
Same problem :cry:

**Comment by jcbrbn** [comment]
Same problem here.
I reinstalled the previous version (v1.16.1) and "uploadOnSave" is working again.

**Comment by rigiddesign** [comment]
> Same problem here. I reinstalled the previous version (v1.16.1) and "uploadOnSave" is working again.

Yeah, same, @jcbrbn, I also installed the previous version, and it's working as before.

**Comment by bronze21** [comment]
Same problem here.
Even with reinstalled to version 1.16.0 still have error config not found
[06-18 00:50:00] [warn] ENOENT: no such file or directory, open '/home/bronze/.ssh/config' load /home/bronze/.ssh/config failed
[06-18 00:50:05] [trace] run command 'Toggle Output Panel'
[06-18 00:50:21] [trace] run command 'Upload File'
[06-18 00:50:21] [error] Error: Config Not Found. (FILE_PATH)
    at Object.l (/home/bronze/.vscode/extensions/natizyskunk.sftp-1.16.0/dist/extension.js:2:292499)
    at t.default.<anonymous> (/home/bronze/.vscode/extensions/natizyskunk.sftp-1.16.0/dist/extension.js:2:221399)
    at Generator.next (<anonymous>)
    at /home/bronze/.vscode/extensions/natizyskunk.sftp-1.16.0/dist/extension.js:2:220593
    at new Promise (<anonymous>)
    at r (/home/bronze/.vscode/extensions/natizyskunk.sftp-1.16.0/dist/extension.js:2:220338)
    at /home/bronze/.vscode/extensions/natizyskunk.sftp-1.16.0/dist/extension.js:2:221340
    at Array.map (<anonymous>)
    at t.default.<anonymous> (/home/bronze/.vscode/extensions/natizyskunk.sftp-1.16.0/dist/extension.js:2:221332)
    at Generator.next (<anonymous>)
    at s (/home/bronze/.vscode/extensions/natizyskunk.sftp-1.16.0/dist/extension.js:2:220395)

**Comment by Natizyskunk** [comment]
@rigiddesign, @FlipZoomMedia, @dsanmartin, @jcbrbn,
I'm really sorry to hear that. Please can everyone enable Debug and share there logs please ?
I'm gonna take a look at it 🙂

**Comment by rigiddesign** [comment]
Thank you, @Natizyskunk . I provided mine above, but let me know if you need anything else.

**Comment by Be-Mann** [comment]
With me the same, so that one can see also times the difference of the two versions, I deposited excerpts from both times.

Log extract from the v1.16.3:
`[06-19 10:53:51] [info] Using profile: dev
[06-19 10:53:51] [warn] ENOENT: no such file or directory, open 'C:\Users\Be_Mann\.ssh\config' load C:\Users\Be_Mann\.ssh\config failed
[06-19 10:53:51] [info] [file-save] \\NAS\Websites\siteXY\verification\index.php
[06-19 10:53:51] [error] Error: Config Not Found. (file://nas/Websites/siteXY/verification/index.php)
	at l (b:\Visual Studio Code\data\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296202)
	at Object.<anonymous> (b:\Visual Studio Code\data\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296960)
	at Generator.next (<anonymous>)
	at b:\Visual Studio Code\data\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295920
	at new Promise (<anonymous>)
	at n (b:\Visual Studio Code\data\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295665)
	at Object.<anonymous> (b:\Visual Studio Code\data\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296899)
	at b:\Visual Studio Code\data\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:324013
	at Generator.next (<anonymous>)
	at s (b:\Visual Studio Code\data\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:323056) download \\NAS\Websites\siteXY\verification\index.php
`
Log extract from the v1.16.1:
`[06-19 10:54:52] [info] Using profile: dev
[06-19 10:54:52] [warn] ENOENT: no such file or directory, open 'C:\Users\Be_Mann\.ssh\config' load C:\Users\Be_Mann\.ssh\config failed
[06-19 10:54:52] [info] [file-save] w:\siteXY\verification\index.php
[06-19 10:54:52] [info] Using profile: dev
[06-19 10:54:52] [trace] handle upload file for w:\siteXY\verification\index.php
[06-19 10:54:52] [debug] Custom crypto binding not available
[06-19 10:54:52] [debug] Local ident: 'SSH-2.0-ssh2js1.11.0'
[06-19 10:54:52] [debug] Client: Trying dedi6312.your-server.de on port 22 ...
[06-19 10:54:52] [debug] Socket connected
[06-19 10:54:52] [debug] Remote ident: 'SSH-2.0-mod_sftp'
[06-19 10:54:52] [debug] Outbound: Sending KEXINIT
[06-19 10:54:52] [debug] Inbound: Handshake in progress
[06-19 10:54:52] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[06-19 10:54:52] [debug] Handshake: (remote) KEX method: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,ext-info-s
[06-19 10:54:52] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[06-19 10:54:52] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[06-19 10:54:52] [debug] Handshake: (remote) Host key format: ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[06-19 10:54:52] [debug] Handshake: Host key format: ssh-ed25519
[06-19 10:54:52] [debug] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[06-19 10:54:52] [debug] Handshake: (remote) C->S cipher: aes192-ctr,aes256-ctr,aes128-ctr
[06-19 10:54:52] [debug] Handshake: C->S Cipher: aes128-ctr
[06-19 10:54:52] [debug] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[06-19 10:54:52] [debug] Handshake: (remote) S->C cipher: aes192-ctr,aes256-ctr,aes128-ctr
[06-19 10:54:52] [debug] Handshake: S->C cipher: aes128-ctr
[06-19 10:54:52] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[06-19 10:54:52] [debug] Handshake: (remote) C->S MAC: hmac-sha2-512,hmac-sha2-256
[06-19 10:54:52] [debug] Handshake: C->S MAC: hmac-sha2-256
[06-19 10:54:52] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[06-19 10:54:52] [debug] Handshake: (remote) S->C MAC: hmac-sha2-512,hmac-sha2-256
[06-19 10:54:52] [debug] Handshake: S->C MAC: hmac-sha2-256
[06-19 10:54:52] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[06-19 10:54:52] [debug] Handshake: (remote) C->S compression: none
[06-19 10:54:52] [debug] Handshake: C->S compression: none
[06-19 10:54:52] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[06-19 10:54:52] [debug] Handshake: (remote) S->C compression: none
[06-19 10:54:52] [debug] Handshake: S->C compression: none
[06-19 10:54:52] [debug] Outbound: Sending KEXECDH_INIT
[06-19 10:54:52] [debug] Received DH Reply
[06-19 10:54:52] [debug] Host accepted by default (no verification)
[06-19 10:54:52] [debug] Host accepted (verified)
[06-19 10:54:52] [debug] Outbound: Sending NEWKEYS
[06-19 10:54:52] [debug] Inbound: NEWKEYS
[06-19 10:54:52] [debug] Verifying signature ...
[06-19 10:54:52] [debug] Verified signature
[06-19 10:54:52] [debug] Handshake completed
[06-19 10:54:52] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[06-19 10:54:52] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[06-19 10:54:52] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[06-19 10:54:53] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[06-19 10:54:53] [debug] Client: none auth failed
[06-19 10:54:53] [debug] Outbound: Sending USERAUTH_REQUEST (password)
[06-19 10:54:53] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[06-19 10:54:53] [debug] Client: password auth failed
[06-19 10:54:53] [debug] Outbound: Sending USERAUTH_REQUEST (publickey -- check)
[06-19 10:54:53] [debug] Inbound: Received USERAUTH_PK_OK
[06-19 10:54:53] [debug] Outbound: Sending USERAUTH_REQUEST (publickey)
[06-19 10:54:53] [debug] Inbound: Received USERAUTH_SUCCESS
[06-19 10:54:53] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[06-19 10:54:53] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[06-19 10:54:53] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[06-19 10:54:53] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[06-19 10:54:53] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[06-19 10:54:53] [debug] Inbound: CHANNEL_DATA (r:0, 179)
[06-19 10:54:53] [debug] SFTP: Inbound: Received VERSION (v3, exts:versions,fsync@openssh.com,posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com)
[06-19 10:54:53] [debug] Outbound: Sending CHANNEL_DATA (r:0, 68)
[06-19 10:54:53] [debug] SFTP: Outbound: Buffered MKDIR
[06-19 10:54:53] [debug] Inbound: CHANNEL_DATA (r:0, 45)
[06-19 10:54:53] [debug] SFTP: Inbound: Received STATUS (id:0, 4, "File already exists")
[06-19 10:54:53] [debug] Outbound: Sending CHANNEL_DATA (r:0, 64)
[06-19 10:54:53] [debug] SFTP: Outbound: Buffered LSTAT
[06-19 10:54:53] [debug] Inbound: CHANNEL_DATA (r:0, 45)
[06-19 10:54:53] [debug] SFTP: Inbound: Received ATTRS (id:1)
[06-19 10:54:53] [debug] Outbound: Sending CHANNEL_DATA (r:0, 82)
[06-19 10:54:53] [debug] SFTP: Outbound: Buffered OPEN
[06-19 10:54:53] [debug] Inbound: CHANNEL_DATA (r:0, 29)
[06-19 10:54:53] [debug] SFTP: Inbound: Received HANDLE (id:2)
[06-19 10:54:53] [debug] Outbound: Sending CHANNEL_DATA (r:0, 29)
[06-19 10:54:53] [debug] SFTP: Outbound: Buffered FSTAT
[06-19 10:54:53] [debug] Inbound: CHANNEL_DATA (r:0, 45)
[06-19 10:54:53] [debug] SFTP: Inbound: Received ATTRS (id:3)
[06-19 10:54:53] [debug] Outbound: Sending CHANNEL_DATA (r:0, 37)
[06-19 10:54:53] [debug] SFTP: Outbound: Buffered FSETSTAT
[06-19 10:54:53] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[06-19 10:54:53] [debug] SFTP: Inbound: Received STATUS (id:4, 0, "OK")
[06-19 10:54:54] [debug] Outbound: Sending CHANNEL_DATA (r:0, 7682)
[06-19 10:54:54] [debug] SFTP: Outbound: Sent WRITE (id:5)
[06-19 10:54:54] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[06-19 10:54:54] [debug] SFTP: Inbound: Received STATUS (id:5, 0, "OK")
[06-19 10:54:54] [debug] Outbound: Sending CHANNEL_DATA (r:0, 41)
[06-19 10:54:54] [debug] SFTP: Outbound: Buffered FSETSTAT
[06-19 10:54:54] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[06-19 10:54:54] [debug] SFTP: Inbound: Received STATUS (id:6, 0, "OK")
[06-19 10:54:54] [debug] Outbound: Sending CHANNEL_DATA (r:0, 29)
[06-19 10:54:54] [debug] SFTP: Outbound: Buffered CLOSE
[06-19 10:54:54] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[06-19 10:54:54] [debug] SFTP: Inbound: Received STATUS (id:7, 0, "OK")
[06-19 10:54:54] [info] local ➞ remote w:\siteXY\verification\index.php
`

**Comment by Natizyskunk** [comment]
Related issues : #376

**Comment by jonathanmorgan** [comment]
I have this issue also, I work in a controlled environment, happy to help troubleshoot or test, will try to create debug log output.

**Comment by Natizyskunk** [comment]
@rigiddesign, @FlipZoomMedia, @dsanmartin, @jcbrbn, @Be-Mann, 
This is definitely a bug that has been introduced in the new 1.16.3 release. Please downgrade to 1.16.1 or pre-1.16.2 while we fix this issue.

**Comment by Natizyskunk** [comment]
Related issues : #376, #383, #397, #398, #401

**Comment by rigiddesign** [comment]
How has this not been fixed, nearly THREE years later?

The version that still works does not support servers using newer key-exchange.

**Comment by Natizyskunk** [comment]
⚠️ => https://github.com/Natizyskunk/vscode-sftp?tab=readme-ov-file#%E2%84%B9-infos---20250313

**Comment by flipzoom** [comment]
@rigiddesign switch to https://github.com/heminei/vscode-pro-deployer

**Comment by rigiddesign** [comment]
@flipzoom, thank you for the suggestion.

Ironically, though, the upload on save feature of that doesn't work either! Lol.

I successfully set up a config file, and it uploads if I manually trigger it, but the option "uploadOnSave": true is not working either

**Comment by flipzoom** [comment]
> [@flipzoom](https://github.com/flipzoom), thank you for the suggestion.
> 
> Ironically, though, the upload on save feature of that doesn't work either! Lol.
> 
> I successfully set up a config file, and it uploads if I manually trigger it, but the option "uploadOnSave": true is not working either

@rigiddesign That's strange; it all works fine for me. It actually works better than that extension because it also monitors other modified files and uploads them automatically. For example, when a Less file is built, all modified .min files are automatically uploaded along with it.
