### ISSUE TITLE
1.16.3 / VSStudioCode 

### ISSUE THREAD

**Issue by r2d2r01** [Natizyskunk/vscode-sftp#376]
Hi, I have installed SFTP extension with config below, it's running ok there is one week, but after update extension the option uploadeonsave very practical fails.
Rem:
1. Remote connexion FAI-VPS4 with this sftp.json succeed
2. Menu Right Click / Upload File succeed
Any help would be very appreciated
Frederic

VScode : 1.79.2
Sftp: 1.16.3
OS: W11Pro 

```
{
    "name": "FAI-VPS4",
    "host": "X.X.X.X",
    "protocol": "sftp",
    "port": 22,
    "username": "*******",
    "password": "***************",
    "remotePath": "/var/www/***********/temp",
    "context": "R:/Web-Site/Web-Temp",
    "uploadOnSave": true,
    "useTempFile": false,
    "openSsh": false
}



[06-19 20:25:01] [info] [file-save] D:\_DEV\Temp\Web-Site\Web-Temp\login.php
[06-19 20:25:01] [error] Error: Config Not Found. (file:///d:/_DEV/Temp/Web-Site/Web-Temp/login.php)
    at l (c:\Users\root\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296202)
    at Object.<anonymous> (c:\Users\root\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296960)
    at Generator.next (<anonymous>)
    at c:\Users\root\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295920
    at new Promise (<anonymous>)
    at n (c:\Users\root\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295665)
    at Object.<anonymous> (c:\Users\root\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296899)
    at c:\Users\root\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:324013
    at Generator.next (<anonymous>)
    at s (c:\Users\root\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:323056) download D:\_DEV\Temp\Web-Site\Web-Temp\login.php

```

**Comment by Natizyskunk** [comment]
Related issues : #363

**Comment by r2d2r01** [comment]
Thank's Natan no urgency, take your time, prev. version runs fine.
Frederic

**Comment by Natizyskunk** [comment]
@r2d2r01 I'll try my best to take a look at it this weekend or next week.

**Comment by Natizyskunk** [comment]
@r2d2r01 This is definitely a bug that has been introduced in the new 1.16.3 release. Please downgrade to 1.16.1 or pre-1.16.2 while we fix this issue.

**Comment by Natizyskunk** [comment]
Related issues : #363, #383, #397, #398, #401
