### ISSUE TITLE
sshConfigPath with proxy command doesn't work 

### ISSUE THREAD

**Issue by tareqtms** [Natizyskunk/vscode-sftp#382]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**
I am using proxy command to connect SSH/SFTP which is covered with SSH config file (~/.ssh/config). It works fine when I try to connect ssh or sftp from any command line, but when I try to upload from using this extension, it shows error saying `getaddrinfo ENOTFOUND {domain_name}`, which means it's not getting the config file or not honouring it.  

**To Reproduce**
1. Create ssh config file (~/.ssh/config) : 
```
Host test-dev
  IdentityFile ~/.ssh/id_rsa
  ProxyCommand aws ssm start-session --target instance_id --profile test_aws
  StrictHostKeyChecking no
```
2. Create sftp.json file
```
{
    "name": "AWS-test",
    "host": "test-dev",
    "protocol": "sftp",
    "port": 22,
    "username": "webapp",
    "remotePath": "/var/www/html",
    "sshConfigPath": "~/.ssh/config",
    "privateKeyPath": "~/.ssh/id_rsa",
    "uploadOnSave": false,
    "useTempFile": false,
    "openSsh": true
}
```
3. Try to upload a file

**Expected behavior**
It should use the proxy command described in the ssh config file to connect to the SFTP server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCode Version: 1.79.0
 - Extension Version: v1.16.3

**Extension Logs from Startup** - *required*
[06-27 16:43:41] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[06-27 16:43:41] [debug] register command "Config" from "./commandConfig.ts"
[06-27 16:43:41] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[06-27 16:43:41] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[06-27 16:43:41] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[06-27 16:43:41] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[06-27 16:43:41] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[06-27 16:43:41] [debug] register command "Create File" from "./fileCommandCreateFile.ts"
[06-27 16:43:41] [debug] register command "Create Folder" from "./fileCommandCreateFolder.ts"
[06-27 16:43:41] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[06-27 16:43:41] [debug] register command "Diff" from "./fileCommandDiff.ts"
[06-27 16:43:41] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[06-27 16:43:41] [debug] register command "Download" from "./fileCommandDownload.ts"
[06-27 16:43:41] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[06-27 16:43:41] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[06-27 16:43:41] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[06-27 16:43:41] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[06-27 16:43:41] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[06-27 16:43:41] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[06-27 16:43:41] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[06-27 16:43:41] [debug] register command "List" from "./fileCommandList.ts"
[06-27 16:43:41] [debug] register command "List All" from "./fileCommandListAll.ts"
[06-27 16:43:41] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[06-27 16:43:41] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[06-27 16:43:41] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[06-27 16:43:41] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[06-27 16:43:41] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[06-27 16:43:41] [debug] register command "Upload" from "./fileCommandUpload.ts"
[06-27 16:43:41] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[06-27 16:43:41] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[06-27 16:43:41] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[06-27 16:43:41] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[06-27 16:43:41] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[06-27 16:43:41] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[06-27 16:43:41] [debug] register command "Upload Active File To All Profiles" from "./fileMultiCommandUploadActiveFileToAllProfiles.ts"
[06-27 16:43:41] [debug] register command "Upload Active Folder To All Profiles" from "./fileMultiCommandUploadActiveFolderToAllProfiles.ts"
[06-27 16:43:41] [debug] register command "Upload File To All Profiles" from "./fileMultiCommandUploadFileToAllProfiles.ts"
[06-27 16:43:41] [debug] register command "Upload Folder To All Profiles" from "./fileMultiCommandUploadFolderToAllProfiles.ts"
[06-27 16:43:41] [debug] register command "Upload Force To All Profiles" from "./fileMultiCommandUploadForceToAllProfiles.ts"
[06-27 16:43:41] [debug] register command "Upload Project To All Profiles" from "./fileMultiCommandUploadProjectToAllProfiles.ts"
[06-27 16:43:41] [debug] register command "Upload To All Profiles" from "./fileMultiCommandUploadToAllProfiles.ts"
[06-27 16:43:41] [info] config at /Users/tareq/dev/paperturn/paperturn-2020 {"remotePath":"/var/www/html","uploadOnSave":false,"useTempFile":false,"openSsh":true,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"remoteExplorer":{"order":0},"name":"AWS-Tareq","host":"tareq-dev","port":22,"username":"******","sshConfigPath":"/Users/tareq/.ssh/config","privateKeyPath":"/Users/tareq/.ssh/id_ed25519"}
[06-27 16:43:50] [trace] run command 'Upload File'
[06-27 16:43:50] [trace] handle upload file for /Users/tareq/dev/paperturn/paperturn-2020/test2.php
[06-27 16:43:50] [debug] Custom crypto binding not available
[06-27 16:43:50] [debug] Local ident: 'SSH-2.0-ssh2js1.13.0'
[06-27 16:43:50] [debug] Client: Trying tareq-dev on port 22 ...
[06-27 16:43:50] [debug] Socket error: getaddrinfo ENOTFOUND tareq-dev
[06-27 16:43:50] [error] Error: [tareq-dev]: getaddrinfo ENOTFOUND tareq-dev
	at Client.<anonymous> (/Users/tareq/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:283419)
	at Client.emit (node:events:525:35)
	at Socket.<anonymous> (/Users/tareq/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/client.js:807:12)
	at Socket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21) 
[06-27 16:43:50] [debug] Socket closed

**Comment by tianyil1** [comment]
mark.

**Comment by sickerin** [comment]
I also have the same error, `SFTP: Open SSH in Terminal` works, but when using the extension to do anything else, I get `getaddrinfo ENOTFOUND`. My example ssh config

```
Host jump
    HostName jump.io
    Port 2222
    IdentityFile ~/.ssh/id_rsa

Host target
    HostName 10.10.10.10
    ProxyCommand ssh jump -W %h:%p
```
And example sftp.json
```
{
    "name": "target-example",
    "username": "root",
    "host": "target",
    "protocol": "sftp",
    "port": 21,
    "secure": true,
    "sshConfigPath": "~/.ssh/config",
    "privateKeyPath": "~/.ssh/id_rsa",
    "remotePath": "/data/me/",
    "uploadOnSave": false,
    "openSsh": true
}
```

**Comment by jgrills** [comment]
Ran into this yesterday myself. I did some searching and found the node ssh client should have that ability.
https://solutionfall.com/question/can-a-ssh-client-be-created-in-nodejs-that-uses-proxycommand/

I think the problem is that the code that copies the fields from the .ssh/config into the json configuration, 'proxycommand' is missing from this list
https://github.com/Natizyskunk/vscode-sftp/blob/develop/src/core/fileService.ts#L253

**Comment by ziwenhahaha** [comment]
@jgrills Thank you very much for raising the question, I have encountered the same problem. Do you have a solution now?

**Comment by pcasl** [comment]
I came across a similar problem. Any solution to connect to a host with proxycommand? Thanks!

**Comment by ziwenhahaha** [comment]
> I came across a similar problem. Any solution to connect to a host with proxycommand? Thanks!

hi, you can try it under Ubuntu or WSL2. the main problem is the OpenSSL version is not match. The Easiest way is to use it under Linux such as Ubuntu System.

**Comment by pcasl** [comment]
Thanks. But I am running on a MAC. Any suggestions? I can do 'sftp my_host' in the Mac terminal successfully.
