### ISSUE TITLE
 "uploadOnSave": true - stopped working on Win10

### ISSUE THREAD

**Issue by udilgp** [Natizyskunk/vscode-sftp#397]
This might be an issue in other environments but I cannot transfer a file upon save anymore.
This feature was working very well for a while, and recently stopped.
Browsing server from the side pane seems to be working normally.

This is the output during file save:

[07-03 13:01:05] [info] [file-save] C:\Users\someone\Documents\Projects\Repo\PROJ\plugins\file-to-upload-upon-save.ext
[07-03 13:01:05] [error] Error: Config Not Found. (file:///c:/Users/someone/Documents/Projects/Repo/PROJ/plugins/file-to-upload-upon-save.ext)
	at l (c:\Users\someone\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296202)
	at Object.<anonymous> (c:\Users\someone\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296960)
	at Generator.next (<anonymous>)
	at c:\Users\someone\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295920
	at new Promise (<anonymous>)
	at n (c:\Users\someone\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:295665)
	at Object.<anonymous> (c:\Users\someone\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:296899)
	at c:\Users\someone\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:324013
	at Generator.next (<anonymous>)
	at s (c:\Users\someone\.vscode\extensions\natizyskunk.sftp-1.16.3\dist\extension.js:2:323056) download C:\Users\someone\Documents\Projects\Repo\PROJ\plugins\file-to-upload-upon-save.ext

Thanks for this extension.
Please let me know if any additional details are needed.

**Comment by GeekPatrolMiller** [comment]
I can confirm this is happening in Linux as well. Ubuntu 22.04 x86-64 logging on to remote AZURE VM instance via SSH

I get  pretty much the same error message as @udilgp except the path and file name are different. This seems to only happen on Upload on Save. 

`[07-04 10:15:47] [info] [file-save] /nfs/sdb1/HomeFolders/UserName/Documents/ProgrammingProjects/Websites/CompanyName/ProjectName/public_html/FolderName/junk.txt
[07-04 10:15:47] [error] Error: Config Not Found. (file:///nfs/sdb1/HomeFolders/UserName/Documents/ProgrammingProjects/Websites/CompanyName/ProjectName/public_html/FolderName/junk.txt)
	at l (/home/username/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:296202)
	at Object.<anonymous> (/home/username/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:296960)
	at Generator.next (<anonymous>)
	at /home/username/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:295920
	at new Promise (<anonymous>)
	at n (/home/username/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:295665)
	at Object.<anonymous> (/home/username/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:296899)
	at /home/username/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:324013
	at Generator.next (<anonymous>)
	at s (/home/username/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:323056) download /nfs/sdb1/HomeFolders/UserName/Documents/ProgrammingProjects/Websites/CompanyName/ProjectName/public_html/FolderName/junk.txt`


I can always right click the file in the VS Code Explorer and click Upload File and this works flawlessly.

`[07-04 10:14:20] [info] local ➞ remote /home/UserName/Documents/ProgrammingProjects/Websites/CompanyName/ProjectName/public_html/FolderName/test.php`


This is by far the more stable and accurate of the tools that I have used. Keep up the good work...

**Comment by udilgp** [comment]
Thanks for the feedback @GeekPatrolMiller 
Upload on save became a feature which without I feel crippled.
Thanks for the right-click tip. It is a reasonable compromise compared to switching to FileZilla every time I change a file.

Great extension!

**Comment by satiromarra** [comment]
@udilgp To know more about the problem, do you have profiles in your settings?

**Comment by udilgp** [comment]
@satiromarra Normally I have an sftp.json file with a single set of connection details.
One thing worth mentioning is that I add "password" key/value which is not there by default, but has been working perfectly for months or even years?

**Comment by satiromarra** [comment]
@udilgp Did version 1.16.1 work correctly for you?

**Comment by udilgp** [comment]
@satiromarra I think we should start by removing a bit of confusion :)
VS Code lists multiple SFTP extensions which look identical.
One of them is discontinued which is clear.
The other two are by @Natizyskunk and @satiromarra.
Which flavor of SFTP extension is the one associated with this repo and Issue?
Thanks.
![image](https://github.com/Natizyskunk/vscode-sftp/assets/95726041/21add6b1-ee6e-486f-b4f0-50cd87e18bec)

**Comment by satiromarra** [comment]
@udilgp The official extension is currently that of @Natizyskunk and now I am also part of this extension as collaborator.

The one under my name is a fork and has a different process and development, which I am preparing to integrate it into this branch.

**Comment by udilgp** [comment]
Thanks for clarifying @satiromarra 
I'm currently on v1.16.3 and yesterday was still seeing the issue.
Right-Click a file on the SFTP file explorer and selecting upload did work.

**Comment by satiromarra** [comment]
@udilgp you can downgrade to 1.16.1 version and tries again?

**Comment by GeekPatrolMiller** [comment]
I also have a sftp.json file in the root of the project and has been working for about a year with no issues. It has been a few weeks since I last worked in VS Code so I am uncertain if the issue appeared at the last update or not. I can confirm based on the changelog that this extension was working properly during v1.16.1 and I will also try downgrading.

Here is my config file for reference(some text altered to protect sensitive details):
`{
    "name": "ProjectName",
    "host": "project.domin.com",
    "protocol": "sftp",
    "port": 22,
    "username": "username",
    "privateKeyPath": "/home/gmiller/.ssh/project_user.pem",
    "remotePath": "/home/project/",
    "uploadOnSave": true,
    "ignore": [
        ".awstats-htpasswd",
        ".bash_history",
        ".bash_logout",
        ".bashrc",
        ".cache",
        ".config",
        ".filemin",
        ".local",
        ".profile",
        ".ssh",
        ".awstats-htpasswd",
        ".vscode-server",
        ".wget-hsts",
        "Maildir",
        "awstats",
        "cgi-bin",
        "etc",
        "fcgi-bin",
        "homes",
        "logs",
        "ssl.*",
        "tmp",
        "__pycache__",
        ".vscode", 
        ".git", 
        ".DS_Store", 
        "README.md",
    ]
}
`

The version I am using is this one:
![image](https://github.com/Natizyskunk/vscode-sftp/assets/12386490/e0385a05-9486-4cfb-b110-f10a19a75e06)

**Comment by udilgp** [comment]
> @udilgp you can downgrade to 1.16.1 version and tries again?

I'll try that and report back.

**Comment by GeekPatrolMiller** [comment]
Confirmation: 1.16.1 does work for me

**Comment by udilgp** [comment]
@satiromarra Downgraded to 1.16.1 and it's working again.
Thanks!

**Comment by Natizyskunk** [comment]
@satiromarra thanks for your help. It seems that this bug has been introduced with the new 1.16.3 release. I'm gonna take a look at it and see how I can fix it. Feel free to check the commits between 1.16.1, 1.16.2-pre & 1.16.3. Maybe you can spot something.

**Comment by Natizyskunk** [comment]
> @udilgp The official extension is currently that of @Natizyskunk and now I am also part of this extension as collaborator.
> 
> The one under my name is a fork and has a different process and development, which I am preparing to integrate it into this branch.

@udilgp I would like to add that @satiromarra has made some amazing progress when I wasn't able to work on the extension and we've now decided to work together for the best 🙂 Some of his work will be merged in this repo but we're gonna do this step by step. His own fork contains others cool features that you can check out and of course try yourself if you want to 😉

**Comment by Natizyskunk** [comment]
Related issues : #363, #376, #383, #398, #401
