### ISSUE TITLE
Error: Config Not Found on Ctlr+S and upload.

### ISSUE THREAD

**Issue by denis-7** [Natizyskunk/vscode-sftp#428]
In the new version 1.16.3 for Linux, this feature has stopped working. An error occurs when trying to save changes:

[09-22 09:21:11] [info] [file-save] /mnt/orcl/Разработка/php/sbol.ts-k.ru/app/Http/Controllers/SbolTest.php
[09-22 09:21:11] [error] Error: Config Not Found. (file:///mnt/orcl/Разработка/php/sbol.ts-k.ru/app/Http/Controllers/SbolTest.php)
at l (/home/denisp/.vscode-oss/extensions/natizyskunk.sftp-1.16.3-universal/dist/extension.js:2:296202)
at Object. (/home/denisp/.vscode-oss/extensions/natizyskunk.sftp-1.16.3-universal/dist/extension.js:2:296960)
at Generator.next ()
at /home/denisp/.vscode-oss/extensions/natizyskunk.sftp-1.16.3-universal/dist/extension.js:2:295920
at new Promise ()
at n (/home/denisp/.vscode-oss/extensions/natizyskunk.sftp-1.16.3-universal/dist/extension.js:2:295665)
at Object. (/home/denisp/.vscode-oss/extensions/natizyskunk.sftp-1.16.3-universal/dist/extension.js:2:296899)
at /home/denisp/.vscode-oss/extensions/natizyskunk.sftp-1.16.3-universal/dist/extension.js:2:324013
at Generator.next ()
at s (/home/denisp/.vscode-oss/extensions/natizyskunk.sftp-1.16.3-universal/dist/extension.js:2:323056)

To solve this problem, we had to roll back to the previous version 1.16.1.

 - OS: Linux 6.1.53-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Sep 13 14:10:57 UTC 2023 x86_64 GNU/Linux
 - VSCode Version Version: 1.82.0, Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
 - Extension Version 1.16.3

**Comment by Greex** [comment]
Same Problem here on windows:

OS: Windows 10
VScode Version 1.83.0
Extension Version: 1.16.3

Version 1.16.1 is working like a charm.

**Comment by andrewdavidjamesburke** [comment]
Same problem here, windows 10

**Comment by gr0undhog** [comment]
Hello together, 

Same problems with Win 11 too.

OS Version: WIn 11 23H2 (22631.3007)
VS Code Version: 1.86.0
Extension Version: 1.16.3

Version 1.16.1 is working
