### ISSUE TITLE
TypeError: Cannot read property 'handle' of undefined

### ISSUE THREAD

**Issue by mansdahlstrom1** [Natizyskunk/vscode-sftp#43]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
Sync Local -> Remote fails with an error.

 
**To Reproduce**
2. Run command '....'
3. See error

**Expected behavior**
File should upload

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCode Version: 1.59.1
 - Extension Version: 1.15.1

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

### config

```
{
  "name": ""*********",
  "host": ""*********",
  "protocol": "sftp",
  "port": 22,
  "username": "*********",
  "password": ""*********",
  "remotePath": "./stg_28b86",
  "uploadOnSave": false,
  "ignore": [
    ".vscode",
    ".git",
    ".gitignore",
    ".DS_Store",
    "/*",
    "!.gitignore",
    "wp-content/*",
    "!wp-content/plugins/",
    "!wp-content/themes/",

    "wp-content/plugins/*",
    "!wp-content/plugins/association-calculator",

    "wp-content/themes/*",
    "!wp-content/theme/essentials-child"
  ]
}
```

### Startup logs

```
[08-24 14:31:44] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[08-24 14:31:44] [debug] register command "Config" from "./commandConfig.ts"
[08-24 14:31:44] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[08-24 14:31:44] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[08-24 14:31:44] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[08-24 14:31:44] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[08-24 14:31:44] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[08-24 14:31:44] [debug] register command "Create File" from "./fileCommandCreateFile.ts"
[08-24 14:31:44] [debug] register command "Create Folder" from "./fileCommandCreateFolder.ts"
[08-24 14:31:44] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[08-24 14:31:44] [debug] register command "Diff" from "./fileCommandDiff.ts"
[08-24 14:31:44] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[08-24 14:31:44] [debug] register command "Download" from "./fileCommandDownload.ts"
[08-24 14:31:44] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[08-24 14:31:44] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[08-24 14:31:44] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[08-24 14:31:44] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[08-24 14:31:44] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[08-24 14:31:44] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[08-24 14:31:44] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[08-24 14:31:44] [debug] register command "List" from "./fileCommandList.ts"
[08-24 14:31:44] [debug] register command "List All" from "./fileCommandListAll.ts"
[08-24 14:31:44] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[08-24 14:31:44] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[08-24 14:31:44] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[08-24 14:31:44] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[08-24 14:31:44] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[08-24 14:31:44] [debug] register command "Upload" from "./fileCommandUpload.ts"
[08-24 14:31:44] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[08-24 14:31:44] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[08-24 14:31:44] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[08-24 14:31:44] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[08-24 14:31:44] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[08-24 14:31:44] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[08-24 14:31:44] [info] config at /Users/mansdahlstrom/Projects/missiontransparency/website/split100-staging {"remotePath":"./stg_28b86","uploadOnSave":false,"useTempFile":true,"downloadOnOpen":false,"ignore":[".vscode",".git",".gitignore",".DS_Store","/*","!.gitignore","wp-content/*","!wp-content/plugins/","!wp-content/themes/","wp-content/plugins/*","!wp-content/plugins/association-calculator","wp-content/themes/*","!wp-content/theme/essentials-child"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"******","host":"******","port":22,"username":"******","password":"******"}
```

### Logs from sync local -> Remote
```
[08-24 14:38:28] [trace] run command 'Sync Local To Remote'
[08-24 14:38:29] [trace] handle sync local ➞ remote for /Users/mansdahlstrom/Projects/missiontransparency/website/split100-staging
[08-24 14:38:29] [debug] Custom crypto binding not available
[08-24 14:38:29] [debug] Client: Trying sftp.split100.se on port 22 ...
[08-24 14:38:29] [debug] Local ident: 'SSH-2.0-ssh2js1.1.0'
[08-24 14:38:29] [debug] Socket connected
[08-24 14:38:29] [debug] Remote ident: 'SSH-2.0-OneSSH-Proxy_1'
[08-24 14:38:29] [debug] Outbound: Sending KEXINIT
[08-24 14:38:29] [debug] Inbound: Handshake in progress
[08-24 14:38:29] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[08-24 14:38:29] [debug] Handshake: (remote) KEX method: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1
[08-24 14:38:29] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[08-24 14:38:29] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[08-24 14:38:29] [debug] Handshake: (remote) Host key format: ssh-dss,ecdsa-sha2-nistp256,ssh-rsa
[08-24 14:38:29] [debug] Handshake: Host key format: ecdsa-sha2-nistp256
[08-24 14:38:29] [debug] Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[08-24 14:38:29] [debug] Handshake: (remote) C->S cipher: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[08-24 14:38:29] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[08-24 14:38:29] [debug] Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[08-24 14:38:29] [debug] Handshake: (remote) S->C cipher: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[08-24 14:38:29] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[08-24 14:38:29] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-24 14:38:29] [debug] Handshake: (remote) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
[08-24 14:38:29] [debug] Handshake: C->S MAC: <implicit>
[08-24 14:38:29] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[08-24 14:38:29] [debug] Handshake: (remote) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
[08-24 14:38:29] [debug] Handshake: S->C MAC: <implicit>
[08-24 14:38:29] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[08-24 14:38:29] [debug] Handshake: (remote) C->S compression: none
[08-24 14:38:29] [debug] Handshake: C->S compression: none
[08-24 14:38:29] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[08-24 14:38:29] [debug] Handshake: (remote) S->C compression: none
[08-24 14:38:29] [debug] Handshake: S->C compression: none
[08-24 14:38:29] [debug] Outbound: Sending KEXECDH_INIT
[08-24 14:38:29] [debug] Received DH Reply
[08-24 14:38:29] [debug] Host accepted by default (no verification)
[08-24 14:38:29] [debug] Host accepted (verified)
[08-24 14:38:29] [debug] Inbound: NEWKEYS
[08-24 14:38:29] [debug] Verifying signature ...
[08-24 14:38:29] [debug] Verified signature
[08-24 14:38:29] [debug] Outbound: Sending NEWKEYS
[08-24 14:38:29] [debug] Handshake completed
[08-24 14:38:29] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[08-24 14:38:29] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[08-24 14:38:29] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[08-24 14:38:29] [debug] Inbound: Received USERAUTH_FAILURE (password,publickey)
[08-24 14:38:29] [debug] Client: none auth failed
[08-24 14:38:29] [debug] Outbound: Sending USERAUTH_REQUEST (password)
[08-24 14:38:29] [debug] Inbound: Received USERAUTH_SUCCESS
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[08-24 14:38:29] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[08-24 14:38:29] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 9)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 183)
[08-24 14:38:29] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com,lsetstat@openssh.com)
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 26)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered MKDIR
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 26)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 14:38:29] [debug] SFTP: Inbound: Received STATUS (id:0, 4, "Failure")
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 22)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered LSTAT
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 22)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[08-24 14:38:29] [debug] SFTP: Inbound: Received ATTRS (id:1)
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 22)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered OPENDIR
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 22)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[08-24 14:38:29] [debug] SFTP: Inbound: Received HANDLE (id:2)
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered READDIR
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 17)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 2909)
[08-24 14:38:29] [debug] SFTP: Inbound: Received NAME (id:3, 23)
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered READDIR
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 17)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 32)
[08-24 14:38:29] [debug] SFTP: Inbound: Received STATUS (id:4, 1, "End of file")
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered CLOSE
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 17)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 14:38:29] [debug] SFTP: Inbound: Received STATUS (id:5, 0, "Success")
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 45)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered OPEN
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 45)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[08-24 14:38:29] [debug] SFTP: Inbound: Received HANDLE (id:6)
[08-24 14:38:29] [info] uploading temp file: stg_28b86/.gitignore.new
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 49)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered OPEN
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 49)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[08-24 14:38:29] [debug] SFTP: Inbound: Received HANDLE (id:7)
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 25)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered FSETSTAT
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 25)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 14:38:29] [debug] SFTP: Inbound: Received STATUS (id:8, 0, "Success")
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 1336)
[08-24 14:38:29] [debug] SFTP: Outbound: Sent WRITE (id:9)
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 1336)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 14:38:29] [debug] SFTP: Inbound: Received STATUS (id:9, 0, "Success")
[08-24 14:38:29] [warn] Can't set modified time to the file because Cannot read property 'handle' of undefined
[08-24 14:38:29] [info] moving from: stg_28b86/.gitignore.new to: stg_28b86/.gitignore
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 33)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered REMOVE
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 33)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 14:38:29] [debug] SFTP: Inbound: Received STATUS (id:10, 0, "Success")
[08-24 14:38:29] [debug] Outbound: Sending CHANNEL_DATA (r:0, 61)
[08-24 14:38:29] [debug] SFTP: Outbound: Buffered RENAME
[08-24 14:38:29] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 61)
[08-24 14:38:29] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 14:38:29] [debug] SFTP: Inbound: Received STATUS (id:11, 0, "Success")
[08-24 14:38:29] [error] TypeError: Cannot read property 'handle' of undefined
	at /Users/mansdahlstrom/.vscode/extensions/natizyskunk.sftp-1.15.1/dist/extension.js:61:121812
	at new Promise (<anonymous>)
	at a.close (/Users/mansdahlstrom/.vscode/extensions/natizyskunk.sftp-1.15.1/dist/extension.js:61:121774)
	at t.default.<anonymous> (/Users/mansdahlstrom/.vscode/extensions/natizyskunk.sftp-1.15.1/dist/extension.js:61:2995)
	at Generator.next (<anonymous>)
	at s (/Users/mansdahlstrom/.vscode/extensions/natizyskunk.sftp-1.15.1/dist/extension.js:61:532)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) when local ➞ remote /Users/mansdahlstrom/Projects/missiontransparency/website/split100-staging/.gitignore

```

**Comment by Natizyskunk** [comment]
It's related to #34.

**Comment by Natizyskunk** [comment]
Should be fixed with next update and new 1.15.2 version.

**Comment by Natizyskunk** [comment]
Could you try new release and tell me if the bug has been fixed please ?

**Comment by mansdahlstrom1** [comment]
@Natizyskunk Seem to be working fine now! Thanks for the quick response and fix!

**Comment by Natizyskunk** [comment]
No problem, i'm glad to hear that ! 😁
