### ISSUE TITLE
uploadOnSave no longer works

### ISSUE THREAD

**Issue by jglazer63** [Natizyskunk/vscode-sftp#440]
Ever since updating to 1.16.3 uploadOnSave no longer functions.  I had to go back to 1.16.1.  Just thought I'd let you know.  Major feature is broken.

Great otherwise!

**Comment by Natizyskunk** [comment]
It's a know nug .Please revert to 1.16.1 or 1.16.2-pre-release until I can fix it.

**Comment by Spirituss** [comment]
I tried 1.16.1 and it doesn't work for me with VSCode.
Here is the log when I try to save file:
```
[error] Error: Failure
	at 101 (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/SFTP.js:2704:19)
	at SFTP.push (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/SFTP.js:278:11)
	at CHANNEL_DATA (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/client.js:525:23)
	at 94 (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/handlers.misc.js:859:16)
	at Protocol.onPayload (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
	at AESGCMDecipherNative.decrypt (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/crypto.js:987:26)
	at Protocol.parsePacket [as _parse] (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
	at Protocol.parse (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
	at Socket.<anonymous> (/Users/user/.vscode/extensions/natizyskunk.sftp-1.16.1/node_modules/ssh2/lib/client.js:713:21)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23) download /Users/user/YAML/test.yaml
[debug] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[debug] Inbound: Received REQUEST_FAILURE
```
