### ISSUE TITLE
Upload error - some files do not upload, some do....

### ISSUE THREAD

**Issue by 4044ever** [Natizyskunk/vscode-sftp#460]
**Describe the bug**
Some files, but not all, fail to upload.

**Desktop (please complete the following information):**
 - OS: [e.g. Win 10
 - VSCode Version [e.g. 1.85.1]
 - Extension Version [e.g. 1.16.3]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

Manual file upload, no. 1 worked, no 2. failed....

```
[01-02 13:58:03] [info] local ➞ remote g:\web\Hugo\5day3\public\de\faq\index.html

[01-02 13:58:55] [error] Error: Failure
	at 101 (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\SFTP.js:2854:19)
	at SFTP.push (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\SFTP.js:278:11)
	at CHANNEL_DATA (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\client.js:587:23)
	at 94 (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\handlers.misc.js:930:16)
	at Protocol.onPayload (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\Protocol.js:2052:10)
	at AESGCMDecipherNative.decrypt (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\crypto.js:987:26)
	at Protocol.parsePacket [as _parse] (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\Protocol.js:2021:25)
	at Protocol.parse (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\Protocol.js:306:16)
	at Socket.<anonymous> (c:\Users\Xile_home\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\client.js:775:21)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23) when local ➞ remote g:\web\Hugo\5day3\public\de\generelles\index.html
```

**Comment by 4044ever** [comment]
I found the error!

It was caused by "server full" and was not related to SFTP 

Might be a good idea to put that into the FAQ
