### ISSUE TITLE
Error: Packet length 1113682792 exceeds max length of 262144

### ISSUE THREAD

**Issue by DrDBanner** [Natizyskunk/vscode-sftp#465]
**Do you read the FAQ?**
- [ ] Yes.
- [x ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
I setup a folder pair on an ionos shared host server via sftp protocol. When I connect to the server I get the error  "Error: Packet length 1113682792 exceeds max length of 262144" as per debug console. The remotePath folder has about 4 directories and 25 files in total. I am unsure if this is an extension problem or a server problem since the server itself has a quite tight `ulimit` at 42. The SSH2 library has one or two bug reports on this as well. So I gave it a shot and updated the ssh2 library to 1.15.0. Unfortunately this did not fix the issue.

At least this BR may help others facing the issue.

```
[01-16 05:35:01] [debug] Debug output from server: "/kunden/homepages/41/d614569926/htdocs/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding"
[01-16 05:35:01] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[01-16 05:35:01] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[01-16 05:35:01] [debug] Inbound: REQUEST_SUCCESS
[01-16 05:35:01] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[01-16 05:35:01] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[01-16 05:35:01] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[01-16 05:35:01] [debug] Inbound: CHANNEL_DATA (r:0, 14)
[01-16 05:35:01] [debug] SFTP: Inbound: Packet length 1113682792 exceeds max length of 262144
[01-16 05:35:01] [debug] Outbound: Sending CHANNEL_CLOSE (r:0)
[01-16 05:35:01] [debug] Outbound: Sending DISCONNECT (11)
[01-16 05:35:01] [error] Error: Packet length 1113682792 exceeds max length of 262144
	at doFatalSFTPError (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/SFTP.js:2713:15)
	at SFTP.push (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/SFTP.js:220:18)
	at CHANNEL_DATA (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/client.js:587:23)
	at 94 (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/handlers.misc.js:930:16)
	at Protocol.onPayload (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/Protocol.js:2052:10)
	at AESGCMDecipherNative.decrypt (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/crypto.js:987:26)
	at Protocol.parsePacket [as _parse] (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
	at Protocol.parse (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/Protocol.js:306:16)
	at Socket.<anonymous> (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/client.js:775:21)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23) 
[01-16 05:35:01] [debug] Socket ended
[01-16 05:35:01] [debug] Socket closed
```

Here a complete set from the `list` command.

```
[01-16 05:55:54] [trace] run command 'List'
[01-16 05:56:12] [debug] Custom crypto binding not available
[01-16 05:56:12] [debug] Local ident: 'SSH-2.0-ssh2js1.13.0'
[01-16 05:56:12] [debug] Client: Trying home614569926.1and1-data.host on port 22 ...
[01-16 05:56:12] [debug] Socket connected
[01-16 05:56:13] [debug] Remote ident: 'SSH-2.0-OpenSSH_8.4p1'
[01-16 05:56:13] [debug] Outbound: Sending KEXINIT
[01-16 05:56:13] [debug] Inbound: Handshake in progress
[01-16 05:56:13] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,ext-info-c
[01-16 05:56:13] [debug] Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com
[01-16 05:56:13] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[01-16 05:56:13] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[01-16 05:56:13] [debug] Handshake: (remote) Host key format: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
[01-16 05:56:13] [debug] Handshake: Host key format: ssh-ed25519
[01-16 05:56:13] [debug] Handshake: (local) C->S cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[01-16 05:56:13] [debug] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[01-16 05:56:13] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[01-16 05:56:13] [debug] Handshake: (local) S->C cipher: aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
[01-16 05:56:13] [debug] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[01-16 05:56:13] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[01-16 05:56:13] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[01-16 05:56:13] [debug] Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[01-16 05:56:13] [debug] Handshake: C->S MAC: <implicit>
[01-16 05:56:13] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[01-16 05:56:13] [debug] Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[01-16 05:56:13] [debug] Handshake: S->C MAC: <implicit>
[01-16 05:56:13] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[01-16 05:56:13] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[01-16 05:56:13] [debug] Handshake: C->S compression: none
[01-16 05:56:13] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[01-16 05:56:13] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[01-16 05:56:13] [debug] Handshake: S->C compression: none
[01-16 05:56:13] [debug] Outbound: Sending KEXECDH_INIT
[01-16 05:56:13] [debug] Received DH Reply
[01-16 05:56:13] [debug] Host accepted by default (no verification)
[01-16 05:56:13] [debug] Host accepted (verified)
[01-16 05:56:13] [debug] Outbound: Sending NEWKEYS
[01-16 05:56:13] [debug] Inbound: NEWKEYS
[01-16 05:56:13] [debug] Verifying signature ...
[01-16 05:56:13] [debug] Verified signature
[01-16 05:56:13] [debug] Handshake completed
[01-16 05:56:13] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[01-16 05:56:13] [debug] Inbound: Received EXT_INFO
[01-16 05:56:13] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[01-16 05:56:13] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[01-16 05:56:13] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[01-16 05:56:13] [debug] Client: none auth failed
[01-16 05:56:13] [debug] Outbound: Sending USERAUTH_REQUEST (publickey -- check)
[01-16 05:56:13] [debug] Inbound: Received USERAUTH_PK_OK
[01-16 05:56:13] [debug] Outbound: Sending USERAUTH_REQUEST (publickey)
[01-16 05:56:13] [debug] Inbound: Received USERAUTH_SUCCESS
[01-16 05:56:13] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[01-16 05:56:13] [debug] Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
[01-16 05:56:13] [debug] Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
[01-16 05:56:13] [debug] Inbound: Received DEBUG
[01-16 05:56:13] [debug] Debug output from server: "/kunden/homepages/41/d614569926/htdocs/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding"
[01-16 05:56:13] [debug] Inbound: Received DEBUG
[01-16 05:56:13] [debug] Debug output from server: "/kunden/homepages/41/d614569926/htdocs/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding"
[01-16 05:56:13] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[01-16 05:56:13] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[01-16 05:56:13] [debug] Inbound: REQUEST_SUCCESS
[01-16 05:56:13] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[01-16 05:56:13] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[01-16 05:56:13] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[01-16 05:56:13] [debug] Inbound: CHANNEL_DATA (r:0, 14)
[01-16 05:56:13] [debug] SFTP: Inbound: Packet length 1113682792 exceeds max length of 262144
[01-16 05:56:13] [debug] Outbound: Sending CHANNEL_CLOSE (r:0)
[01-16 05:56:13] [debug] Outbound: Sending DISCONNECT (11)
[01-16 05:56:13] [error] Error: Packet length 1113682792 exceeds max length of 262144
	at doFatalSFTPError (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/SFTP.js:2713:15)
	at SFTP.push (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/SFTP.js:220:18)
	at CHANNEL_DATA (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/client.js:587:23)
	at 94 (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/handlers.misc.js:930:16)
	at Protocol.onPayload (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/Protocol.js:2052:10)
	at AESGCMDecipherNative.decrypt (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/crypto.js:987:26)
	at Protocol.parsePacket [as _parse] (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/Protocol.js:2021:25)
	at Protocol.parse (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/protocol/Protocol.js:306:16)
	at Socket.<anonymous> (/Users/rosieres/.vscode/extensions/natizyskunk.sftp-1.16.3/node_modules/ssh2/lib/client.js:775:21)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23) 
[01-16 05:56:13] [debug] Socket ended
[01-16 05:56:13] [debug] Socket closed
```

**To Reproduce**
1. Go to 'sftp'
2. Run command 'list'
3. See error

**Expected behavior**
List the files

**Desktop (please complete the following information):**
 - OS: -> MacOS 13.6.3 (22G436) Ventura
 - VSCode Version -> 1.85.1
 - Extension Version -> 1.16.3

**Comment by DrDBanner** [comment]
Found later on issue #235 and indeed it was the same cause. I had an echo statement in the server greeting. When I removed it from the .bashrc the issue was gone.
