### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by Harphiner** [Natizyskunk/vscode-sftp#475]
When I write the sftp configuration file, it shows that I have been connected to the remote correctly, but no matter what file is uploaded, even if it is a small file, the error message "Packet length 1027423776 exceeds max length of 262144" will pop up.
The specific error message is:

[03-09 15:11:38] [error] Error: Packet length 1027423776 exceeds max length of 262144
    at doFatalSFTPError (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\SFTP.js:2713:15)
    at SFTP.push (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\SFTP.js:220:18)
    at CHANNEL_DATA (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\client.js:587:23)
    at 94 (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\handlers.misc.js:930:16)
    at Protocol.onPayload (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\Protocol.js:2052:10)
    at AESGCMDecipherNative.decrypt (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\crypto.js:987:26)
    at Protocol.parsePacket [as _parse] (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\Protocol.js:2021:25)
    at Protocol.parse (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\protocol\Protocol.js:306:16)
    at Socket.<anonymous> (c:\Users\WIN11\.vscode\extensions\natizyskunk.sftp-1.16.3\node_modules\ssh2\lib\client.js:775:21)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by Harphiner** [comment]
Okay, I've solved my problem, because my remote server will output some information in the boot file, just remove these related configurations.
