### ISSUE TITLE
Another config not found issue

### ISSUE THREAD

**Issue by Degilio** [Natizyskunk/vscode-sftp#490]
**Do you read the FAQ?**
- [ X] Yes.
- [x] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
When I try to upload or download a file I get a config not found error. My sftp.json file is in the .vscode directory and contains the following information:
[
    {
        "name": "ATS1",
        "host": "Redacted",
        "context": "Just Random Code",
        "protocol": "sftp",
        "port": 22,
        "username": "Redacted",
        "remotePath": "/u/redacted",
        "uploadOnSave": false,
        "useTempFile": false,
        "openSsh": false
    },
    {
        "name": "Jupyter",
        "host": "Redacted",
        "context": "Jupyter Notebook Stuff",
        "protocol": "sftp",
        "port": 22,
        "username": "Redacted",
        "remotePath": "/shared/python_utilities/rebel/workspace",
        "uploadOnSave": false,
        "useTempFile": false,
        "openSsh": false
    }
]
If you look at the trace below - It clearly shows the config items shown above picked up in the trace..I removed almost every other extension  (installed the Python, base Gt and Jupyter extensions as well as this one)
**To Reproduce**
2. Run command '....'
3. See error

**Expected behavior**
Expected the file to be uploaded or downloaded.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Sonoma 4.14.5
 - VSCode Version 1.89.1
 - Extension Version 1.16.3

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

[05-24 09:52:57] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[05-24 09:52:57] [debug] register command "Config" from "./commandConfig.ts"
[05-24 09:52:57] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[05-24 09:52:57] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[05-24 09:52:57] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[05-24 09:52:57] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[05-24 09:52:57] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[05-24 09:52:57] [debug] register command "Create File" from "./fileCommandCreateFile.ts"
[05-24 09:52:57] [debug] register command "Create Folder" from "./fileCommandCreateFolder.ts"
[05-24 09:52:57] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[05-24 09:52:57] [debug] register command "Diff" from "./fileCommandDiff.ts"
[05-24 09:52:57] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[05-24 09:52:57] [debug] register command "Download" from "./fileCommandDownload.ts"
[05-24 09:52:57] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[05-24 09:52:57] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[05-24 09:52:57] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[05-24 09:52:57] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[05-24 09:52:57] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[05-24 09:52:57] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[05-24 09:52:57] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[05-24 09:52:57] [debug] register command "List" from "./fileCommandList.ts"
[05-24 09:52:57] [debug] register command "List All" from "./fileCommandListAll.ts"
[05-24 09:52:57] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[05-24 09:52:57] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[05-24 09:52:57] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[05-24 09:52:57] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[05-24 09:52:57] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[05-24 09:52:57] [debug] register command "Upload" from "./fileCommandUpload.ts"
[05-24 09:52:57] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[05-24 09:52:57] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[05-24 09:52:57] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[05-24 09:52:57] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[05-24 09:52:57] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[05-24 09:52:57] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[05-24 09:52:57] [debug] register command "Upload Active File To All Profiles" from "./fileMultiCommandUploadActiveFileToAllProfiles.ts"
[05-24 09:52:57] [debug] register command "Upload Active Folder To All Profiles" from "./fileMultiCommandUploadActiveFolderToAllProfiles.ts"
[05-24 09:52:57] [debug] register command "Upload File To All Profiles" from "./fileMultiCommandUploadFileToAllProfiles.ts"
[05-24 09:52:57] [debug] register command "Upload Folder To All Profiles" from "./fileMultiCommandUploadFolderToAllProfiles.ts"
[05-24 09:52:57] [debug] register command "Upload Force To All Profiles" from "./fileMultiCommandUploadForceToAllProfiles.ts"
[05-24 09:52:57] [debug] register command "Upload Project To All Profiles" from "./fileMultiCommandUploadProjectToAllProfiles.ts"
[05-24 09:52:57] [debug] register command "Upload To All Profiles" from "./fileMultiCommandUploadToAllProfiles.ts"
[05-24 09:52:57] [info] config at /Users/Redacted/Documents/GitHub/Just Random Code {"remotePath":"/u/redacted","uploadOnSave":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"remoteExplorer":{"order":0},"name":"ATS1","host":"Redacted","context":"./Just Random Code","port":22,"username":"******"}
[05-24 09:52:57] [info] config at /Users/Redacted/Documents/GitHub/Jupyter Notebook Stuff {"remotePath":"/u/redacted","uploadOnSave":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"remoteExplorer":{"order":0},"name":"Jupyter","host":"Redacted","context":"./Jupyter Notebook Stuff","port":22,"username":"******"}
[05-24 09:54:07] [trace] run command 'Upload File'
[05-24 09:54:07] [error] Error: Config Not Found. (file:///Users/Redacted/Documents/GitHub/experimental_code/Just Random Code/'IDC3009I'.yml)
	at Object.l (/Users/Redacted/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:296202)
	at t.default.<anonymous> (/Users/Redacted/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:221424)
	at Generator.next (<anonymous>)
	at /Users/Redacted/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:220593
	at new Promise (<anonymous>)
	at n (/Users/Redacted/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:220338)
	at /Users/Redacted/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:221365
	at Array.map (<anonymous>)
	at t.default.<anonymous> (/Users/Redacted/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:221357)
	at Generator.next (<anonymous>)
	at s (/Users/Redacted/.vscode/extensions/natizyskunk.sftp-1.16.3/dist/extension.js:2:220395)

**Comment by kenjican** [comment]
I have the same issue,,,  two hosts , one uploads success, another is "config not found"

**Comment by Natizyskunk** [comment]
Please stop opening new issues when there are already multiple ones about the same bug. Just search for similar issues and comment on thoses 😊
