### ISSUE TITLE
Conflict With Live Sass Compiler After(?) Sync

### ISSUE THREAD

**Issue by black-eye** [Natizyskunk/vscode-sftp#57]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
This issue is rather strange. There has to be 2 factors to trigger this issue:
1. [Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass) has to be installed and activated
2. There has to be at least one .scss file in the project

It doesn't matter how the Live Sass Compiler is set up, or what is the content of .scss file (it can be even empty).

After syncing local to remote, this popup appears:

![obrazek](https://user-images.githubusercontent.com/5634870/131274842-2b7d2c49-f403-486b-8f68-8c4648b974f5.png)

It seems, that this message isn't directly connected to SFTP sync procedure and it also seems, that the files are all transfered to sftp correctly. There are also no SFTP related errors in the console.

**To Reproduce**
1. Install [Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass) and activate it
2. Start a project with at least one .scss file
3. Setup SFTP Sync
4. Try to sync Local to Remote
5. Just after sync procedure is complete, the popup mentioned above appears.
6. Disable Live Sass Compiler or delete the .scss file and the problem is gone.

!! It is absolutely essential to reopen VSCode after every change, othervice the change won't take an effect!

**Expected behavior**
The popup won't be shown ;-)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Win 10
 - VSCode Version: 1.59.1
 - Extension Version: 1.15.2

**Extension Logs from Startup** - *required*

[08-30 04:30:08] [debug] register command "Cancel All Transfer" from "./commandCancelAllTransfer.ts"
[08-30 04:30:08] [debug] register command "Config" from "./commandConfig.ts"
[08-30 04:30:08] [debug] register command "List Active Folder" from "./commandListActiveFolder.ts"
[08-30 04:30:08] [debug] register command "Open Ssh Connection" from "./commandOpenSshConnection.ts"
[08-30 04:30:08] [debug] register command "Set Profile" from "./commandSetProfile.ts"
[08-30 04:30:08] [debug] register command "Toggle Output Panel" from "./commandToggleOutputPanel.ts"
[08-30 04:30:08] [debug] register command "Upload Changed Files" from "./commandUploadChangedFiles.ts"
[08-30 04:30:08] [debug] register command "Create File" from "./fileCommandCreateFile.ts"
[08-30 04:30:08] [debug] register command "Create Folder" from "./fileCommandCreateFolder.ts"
[08-30 04:30:08] [debug] register command "Delete Remote" from "./fileCommandDeleteRemote.ts"
[08-30 04:30:08] [debug] register command "Diff" from "./fileCommandDiff.ts"
[08-30 04:30:08] [debug] register command "Diff Active File" from "./fileCommandDiffActiveFile.ts"
[08-30 04:30:08] [debug] register command "Download" from "./fileCommandDownload.ts"
[08-30 04:30:08] [debug] register command "Download Active File" from "./fileCommandDownloadActiveFile.ts"
[08-30 04:30:08] [debug] register command "Download Active Folder" from "./fileCommandDownloadActiveFolder.ts"
[08-30 04:30:08] [debug] register command "Download File" from "./fileCommandDownloadFile.ts"
[08-30 04:30:08] [debug] register command "Download Folder" from "./fileCommandDownloadFolder.ts"
[08-30 04:30:08] [debug] register command "Download Force" from "./fileCommandDownloadForce.ts"
[08-30 04:30:08] [debug] register command "Download Project" from "./fileCommandDownloadProject.ts"
[08-30 04:30:08] [debug] register command "Edit In Local" from "./fileCommandEditInLocal.ts"
[08-30 04:30:08] [debug] register command "List" from "./fileCommandList.ts"
[08-30 04:30:08] [debug] register command "List All" from "./fileCommandListAll.ts"
[08-30 04:30:08] [debug] register command "Reveal In Explorer" from "./fileCommandRevealInExplorer.ts"
[08-30 04:30:08] [debug] register command "Reveal In Remote Explorer" from "./fileCommandRevealInRemoteExplorer.ts"
[08-30 04:30:08] [debug] register command "Sync Both Directions" from "./fileCommandSyncBothDirections.ts"
[08-30 04:30:08] [debug] register command "Sync Local To Remote" from "./fileCommandSyncLocalToRemote.ts"
[08-30 04:30:08] [debug] register command "Sync Remote To Local" from "./fileCommandSyncRemoteToLocal.ts"
[08-30 04:30:08] [debug] register command "Upload" from "./fileCommandUpload.ts"
[08-30 04:30:08] [debug] register command "Upload Active File" from "./fileCommandUploadActiveFile.ts"
[08-30 04:30:08] [debug] register command "Upload Active Folder" from "./fileCommandUploadActiveFolder.ts"
[08-30 04:30:08] [debug] register command "Upload File" from "./fileCommandUploadFile.ts"
[08-30 04:30:08] [debug] register command "Upload Folder" from "./fileCommandUploadFolder.ts"
[08-30 04:30:08] [debug] register command "Upload Force" from "./fileCommandUploadForce.ts"
[08-30 04:30:08] [debug] register command "Upload Project" from "./fileCommandUploadProject.ts"
[08-30 04:30:09] [info] config at d:\.work\sftp-test\sftp-test {"remotePath":"./","uploadOnSave":true,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[".vscode",".git",".DS_Store"],"concurrency":4,"protocol":"ftp","connectTimeout":10000,"interactiveAuth":false,"secure":false,"remoteTimeOffsetInHours":0,"name":"Daihatsu","host":"daihatsu-auto.cz","port":21,"username":"******","password":"******","syncOption":{"update":true,"delete":true},"syncMode":"full","profiles":{"sftp-test-ostra":{"remotePath":"/www/sftp-test/"},"sftp-test-devel":{"remotePath":"/www/sftp-test-devel/"}},"defaultProfile":"sftp-test-ostra"}
[08-30 04:30:12] [trace] run command 'Toggle Output Panel'
[08-30 04:30:17] [trace] run command 'Sync Local To Remote'
[08-30 04:30:18] [info] Using profile: sftp-test-ostra
[08-30 04:30:18] [trace] handle sync local ➞ remote for d:\.work\sftp-test\sftp-test
[08-30 04:30:18] [debug] < '220 FTP server [uvirt91.active24.cz]\r\n'
[08-30 04:30:18] [debug] > USER daihatsuau
[08-30 04:30:18] [debug] < '331 Password required for daihatsuau\r\n'
[08-30 04:30:18] [debug] > PASS ******
[08-30 04:30:18] [debug] < '230 User daihatsuau logged in\r\n'
[08-30 04:30:18] [debug] > FEAT
[08-30 04:30:18] [debug] < '211-Features:\r\n211-AUTH TLS\r\n211-CCC\r\n'
[08-30 04:30:18] [debug] < '211-CLNT\r\n211-EPRT\r\n'
[08-30 04:30:18] [debug] < '211-EPSV\r\n211-HOST\r\n'
[08-30 04:30:18] [debug] < '211-LANG en-US;ru-RU;it-IT.UTF-8;it-IT\r\n211-MDTM\r\n'
[08-30 04:30:18] [debug] < '211-MFF modify;UNIX.group;UNIX.mode;\r\n'
[08-30 04:30:18] [debug] > TYPE I
[08-30 04:30:18] [debug] < '200 Type set to I\r\n'
[08-30 04:30:18] [debug] > PASV
[08-30 04:30:18] [debug] < '227 Entering Passive Mode (31,15,10,73,115,207).\r\n'
[08-30 04:30:18] [debug] > LIST /www
[08-30 04:30:18] [debug] < '150 Opening BINARY mode data connection for file list\r\n'
[08-30 04:30:19] [debug] < '226 Transfer complete\r\n'
[08-30 04:30:19] [debug] > PASV
[08-30 04:30:19] [debug] < '227 Entering Passive Mode (31,15,10,73,115,255).\r\n'
[08-30 04:30:19] [debug] > LIST /www/sftp-test/
[08-30 04:30:19] [debug] < '150 Opening BINARY mode data connection for file list\r\n'
[08-30 04:30:19] [debug] < '226 Transfer complete\r\n'
[08-30 04:30:19] [debug] > PASV
[08-30 04:30:19] [debug] < '227 Entering Passive Mode (31,15,10,73,116,50).\r\n'
[08-30 04:30:19] [debug] > STOR /www/sftp-test/.gitignore
[08-30 04:30:19] [debug] < '150 Opening BINARY mode data connection for /www/sftp-test/.gitignore\r\n'
[08-30 04:30:19] [debug] < '226 Transfer complete\r\n'
[08-30 04:30:19] [debug] > MFMT 20210827110352 /www/sftp-test/.gitignore
[08-30 04:30:19] [debug] < '213 Modify=20210827110352; /www/sftp-test/.gitignore\r\n'
[08-30 04:30:19] [info] local ➞ remote d:\.work\sftp-test\sftp-test\.gitignore
[08-30 04:30:19] [debug] > PASV
[08-30 04:30:19] [debug] < '227 Entering Passive Mode (31,15,10,73,114,126).\r\n'
[08-30 04:30:19] [debug] > STOR /www/sftp-test/index.html
[08-30 04:30:19] [debug] < '150 Opening BINARY mode data connection for /www/sftp-test/index.html\r\n'
[08-30 04:30:19] [debug] < '226 Transfer complete\r\n'
[08-30 04:30:19] [debug] > MFMT 20210830022221 /www/sftp-test/index.html
[08-30 04:30:19] [debug] < '213 Modify=20210830022221; /www/sftp-test/index.html\r\n'
[08-30 04:30:19] [info] local ➞ remote d:\.work\sftp-test\sftp-test\index.html
[08-30 04:30:19] [debug] > PASV
[08-30 04:30:19] [debug] < '227 Entering Passive Mode (31,15,10,73,116,194).\r\n'
[08-30 04:30:19] [debug] > STOR /www/sftp-test/new-page.html
[08-30 04:30:19] [debug] < '150 Opening BINARY mode data connection for /www/sftp-test/new-page.html\r\n'
[08-30 04:30:19] [debug] < '226 Transfer complete\r\n'
[08-30 04:30:19] [debug] > MFMT 20210830022221 /www/sftp-test/new-page.html
[08-30 04:30:19] [debug] < '213 Modify=20210830022221; /www/sftp-test/new-page.html\r\n'
[08-30 04:30:19] [info] local ➞ remote d:\.work\sftp-test\sftp-test\new-page.html
[08-30 04:30:19] [debug] > PASV
[08-30 04:30:19] [debug] < '227 Entering Passive Mode (31,15,10,73,113,203).\r\n'
[08-30 04:30:19] [debug] > STOR /www/sftp-test/page2.html
[08-30 04:30:19] [debug] < '150 Opening BINARY mode data connection for /www/sftp-test/page2.html\r\n'
[08-30 04:30:19] [debug] < '226 Transfer complete\r\n'
[08-30 04:30:19] [debug] > MFMT 20210830022221 /www/sftp-test/page2.html
[08-30 04:30:19] [debug] < '213 Modify=20210830022221; /www/sftp-test/page2.html\r\n'
[08-30 04:30:19] [info] local ➞ remote d:\.work\sftp-test\sftp-test\page2.html
[08-30 04:30:19] [debug] > PASV
[08-30 04:30:19] [debug] < '227 Entering Passive Mode (31,15,10,73,114,241).\r\n'
[08-30 04:30:19] [debug] > STOR /www/sftp-test/page3.html
[08-30 04:30:19] [debug] < '150 Opening BINARY mode data connection for /www/sftp-test/page3.html\r\n'
[08-30 04:30:19] [debug] < '226 Transfer complete\r\n'
[08-30 04:30:19] [debug] > MFMT 20210830022221 /www/sftp-test/page3.html

**JS Error from the console:**
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/editor/contrib/documentSymbols/outlineTree.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/browser/parts/views/customView.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/contrib/scm/browser/scmViewlet.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/contrib/scm/browser/mainPanel.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/contrib/scm/browser/mainPane.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/contrib/scm/browser/repositoryPanel.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/contrib/scm/browser/repositoryPane.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/base/browser/ui/splitview/panelview.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/platform/electron/node/electron.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/c:/Users/blackeye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/platform/electron/electron-sandbox/electron.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
console.ts:137 [Extension Host] (node:292) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
localProcessExtensionHost.ts:272 Extension Host
abstractExtensionService.ts:615 Extension host terminated unexpectedly. Code:  7  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:615
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:40
localProcessExtensionHost.ts:272 Extension Host

**Comment by black-eye** [comment]
OH, an important update: I just checked the debug log and strangely enough the .scss file is not there (including some more files)!

See the short log and the list of files here:

![obrazek](https://user-images.githubusercontent.com/5634870/131278152-07379369-cac6-41b0-8470-d81a67d75167.png)

But what is the most peculiar - ALL the files were tranfered to FTP (I cleaned up the ftp folder before the sync). Now, that's really odd!

And just to complete the full picture, this is the situation without the test.scss file. All the file are in the log, no popup message:

![obrazek](https://user-images.githubusercontent.com/5634870/131278800-18a8d715-23cc-48fc-b019-d3f0c3dc2b76.png)

**Comment by BBvT** [comment]
@black-eye  I had similar problems, which were solved when I switched from Ritwick Dey's Live Sass Compiler to  [ Glenn Marks Live Sass Compiler](https://github.com/glenn2223/vscode-live-sass-compiler)

**Comment by black-eye** [comment]
> 
> 
> @black-eye I had similar problems, which were solved when I switched from Ritwick Dey's Live Sass Compiler to [ Glenn Marks Live Sass Compiler](https://github.com/glenn2223/vscode-live-sass-compiler)

Oh, thanks a ton for your advice! I was looking for Live Sass Compiler fork a while ago, but couldn't find one. It's briliant, somebody took care of it since then.

I gave it a try and the problem seems to be solved indeed. Strangely enough it seems it also fixed SFTP transfering all the files instead of just changed ones. And it's also significantly faster. Several peculiar problems solved at once!

I leave the issue open for @Natizyskunk to decide, wheather he won't find here anything useful, but as for me, the problem is solved.

**Comment by Natizyskunk** [comment]
@black-eye,

thanks for opening this issue.

While exploring for more infos, I've been able to isolate the error that happens when uploading an `.scss` file while the LiveSassCompiler extension is on.

This is now the error i get.
```
RuntimeError: abort(Error: Can't find config for remote resource remote://<remote-host>:22/var/www/test/assets/css?remoteId%3D1%26fsPath%3D%252Fvar%252Fwww%252Ftest%252Fassets%252Fcss.).
Build with -s ASSERTIONS=1 for more info.%c
at process.J (c:\Users\Natizyskunk\.vscode\extensions\natizyskunk.sftp-1.15.2\node_modules\ssh2\lib\protocol\crypto\poly1305.js:20:53)%c
at process.emit (events.js:327:22)%c
at process.EventEmitter.emit (domain.js:467:12)%c
at processPromiseRejections (internal/process/promises.js:245:33)%c
at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

I'm now trying to understand where is this bug comming from.

Hopefully it'll be resolved asap.

For now as @BBvT precognize it you can switched from Ritwick Dey's Live Sass Compiler to [Glenn Marks Live Sass Compiler](https://github.com/glenn2223/vscode-live-sass-compiler).

**Comment by Natizyskunk** [comment]
Related issue : #105

**Comment by Natizyskunk** [comment]
Can't find a simple fix for it.
