### ISSUE TITLE
sync both directions error no such file

### ISSUE THREAD

**Issue by visionm45** [Natizyskunk/vscode-sftp#64]
I sync my project with the sftp server then I make a change to a file using filezilla.  Then when I come back to vscode and run sftp sync both directions then it runs but has an error, saying no such file, when it comes to the file which was changed.

 - OS: mac catalina 10.15.7
 - VSCode Version 1.60.1
 - Extension Version v1.15.3
 
**Extension Logs from Startup** 
`[09-21 17:35:03] [info] config at /Users/daniel/Desktop/godot/tank {"remotePath":"/home/visionm/tank","uploadOnSave":false,"useTempFile":false,"openSsh":false,"downloadOnOpen":false,"ignore":[".DS_Store",".import",".vscode",".git"],"concurrency":4,"protocol":"sftp","connectTimeout":10000,"interactiveAuth":false,"secure":true,"remoteTimeOffsetInHours":0,"name":"Gcloud","host":"34.125.39.213","port":22,"limitOpenFilesOnRemote":true,"username":"******","password":"******","watcher":{"files":"**","autoUpload":false,"autoDelete":false}}`

**error log
```
[09-21 17:29:48] [debug] Inbound: CHANNEL_DATA (r:0, 33)
[09-21 17:29:48] [debug] SFTP: Inbound: Received STATUS (id:3381, 2, "No such file")
[09-21 17:29:48] [error] Error: No such file
    at 101 (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/protocol/SFTP.js:2618:19)
    at SFTP.push (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/protocol/SFTP.js:278:11)
    at CHANNEL_DATA (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/client.js:525:23)
    at 94 (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/protocol/handlers.misc.js:859:16)
    at Protocol.onPayload (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/protocol/Protocol.js:2024:10)
    at AESGCMDecipherNative.decrypt (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/protocol/crypto.js:992:26)
    at Protocol.parsePacket [as _parse] (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/protocol/Protocol.js:1993:25)
    at Protocol.parse (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/protocol/Protocol.js:292:16)
    at Socket.<anonymous> (/Users/daniel/.vscode-oss/extensions/natizyskunk.sftp-1.15.3/node_modules/ssh2/lib/client.js:712:21)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when remote ➞ local /Users/daniel/Desktop/godot/tank/Camera2D.gd
```

**Comment by Natizyskunk** [comment]
I'm not able to reproduce the error on my end. Everything works fine for me. Maybe there is a bug with MacOS but i doubt it.
For now this is what i can recommend you :
- Method 1 : Delete the file locally and then on the parent folder click right and chose `Sync Remote -> Local`. It should download the modified file with no bug.
- Method 2 : Go to the SFTP remote explorer tab, find your file and then click right and chose `Edit in Local`.
