### ISSUE TITLE
[error] TypeError: Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by tsingchan** [Natizyskunk/vscode-sftp#81]
**Do you read the FAQ?**
- [x] Yes.
- [ ] [I am going to read now.](https://github.com/Natizyskunk/vscode-sftp/blob/master/FAQ.md)

**Describe the bug**
[11-03 11:14:53] [trace] run command 'Upload File'
[11-03 11:14:53] [warn] ENOENT: no such file or directory, open 'C:\Users\admin\.ssh\config' load C:\Users\admin\.ssh\config failed
[11-03 11:14:53] [trace] handle upload file for e:\src\xxxx\readme.md
[11-03 11:14:53] [debug] Custom crypto binding not available
[11-03 11:14:53] [debug] Client: Trying 192.168.232.131 on port 22 ...
[11-03 11:14:53] [debug] Local ident: 'SSH-2.0-ssh2js1.4.0'
[11-03 11:14:53] [debug] Socket connected
[11-03 11:14:53] [debug] Remote ident: 'SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5'
[11-03 11:14:53] [debug] Outbound: Sending KEXINIT
[11-03 11:14:53] [debug] Inbound: Handshake in progress
[11-03 11:14:53] [debug] Handshake: (local) KEX method: curve25519-sha256@libssh.org,curve25519-sha256,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512
[11-03 11:14:53] [debug] Handshake: (remote) KEX method: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1
[11-03 11:14:53] [debug] Handshake: KEX algorithm: curve25519-sha256@libssh.org
[11-03 11:14:53] [debug] Handshake: (local) Host key format: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
[11-03 11:14:53] [debug] Handshake: (remote) Host key format: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[11-03 11:14:53] [debug] Handshake: Host key format: ssh-ed25519
[11-03 11:14:53] [debug] Handshake: (local) C->S cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[11-03 11:14:53] [debug] Handshake: (remote) C->S cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[11-03 11:14:53] [debug] Handshake: C->S Cipher: aes128-gcm@openssh.com
[11-03 11:14:53] [debug] Handshake: (local) S->C cipher: aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
[11-03 11:14:53] [debug] Handshake: (remote) S->C cipher: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[11-03 11:14:53] [debug] Handshake: S->C cipher: aes128-gcm@openssh.com
[11-03 11:14:53] [debug] Handshake: (local) C->S MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[11-03 11:14:53] [debug] Handshake: (remote) C->S MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[11-03 11:14:53] [debug] Handshake: C->S MAC: <implicit>
[11-03 11:14:53] [debug] Handshake: (local) S->C MAC: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[11-03 11:14:53] [debug] Handshake: (remote) S->C MAC: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[11-03 11:14:53] [debug] Handshake: S->C MAC: <implicit>
[11-03 11:14:53] [debug] Handshake: (local) C->S compression: none,zlib@openssh.com,zlib
[11-03 11:14:53] [debug] Handshake: (remote) C->S compression: none,zlib@openssh.com
[11-03 11:14:53] [debug] Handshake: C->S compression: none
[11-03 11:14:53] [debug] Handshake: (local) S->C compression: none,zlib@openssh.com,zlib
[11-03 11:14:53] [debug] Handshake: (remote) S->C compression: none,zlib@openssh.com
[11-03 11:14:53] [debug] Handshake: S->C compression: none
[11-03 11:14:53] [debug] Outbound: Sending KEXECDH_INIT
[11-03 11:14:53] [debug] Received DH Reply
[11-03 11:14:53] [debug] Host accepted by default (no verification)
[11-03 11:14:53] [debug] Host accepted (verified)
[11-03 11:14:53] [debug] Outbound: Sending NEWKEYS
[11-03 11:14:53] [debug] Inbound: NEWKEYS
[11-03 11:14:53] [debug] Verifying signature ...
[11-03 11:14:53] [debug] Verified signature
[11-03 11:14:53] [debug] Handshake completed
[11-03 11:14:53] [debug] Outbound: Sending SERVICE_REQUEST (ssh-userauth)
[11-03 11:14:53] [debug] Inbound: Received SERVICE_ACCEPT (ssh-userauth)
[11-03 11:14:53] [debug] Outbound: Sending USERAUTH_REQUEST (none)
[11-03 11:14:53] [debug] Inbound: Received USERAUTH_FAILURE (publickey,password)
[11-03 11:14:53] [debug] Client: none auth failed
[11-03 11:14:53] [debug] Outbound: Sending USERAUTH_REQUEST (password)
[11-03 11:14:53] [debug] Inbound: Received USERAUTH_SUCCESS
[11-03 11:14:53] [debug] Outbound: Sending CHANNEL_OPEN (r:0, session)
[11-03 11:14:54] [debug] Inbound: GLOBAL_REQUEST (hostkeys-00@openssh.com)
[11-03 11:14:54] [debug] Outbound: Sending GLOBAL_REQUEST (hostkeys-prove-00@openssh.com)
[11-03 11:14:54] [debug] Inbound: CHANNEL_OPEN_CONFIRMATION (r:0, s:0)
[11-03 11:14:54] [debug] Outbound: Sending CHANNEL_REQUEST (r:0, subsystem: sftp)
[11-03 11:14:54] [debug] Inbound: REQUEST_SUCCESS
[11-03 11:14:54] [debug] Inbound: CHANNEL_WINDOW_ADJUST (r:0, 2097152)
[11-03 11:14:54] [debug] Inbound: CHANNEL_SUCCESS (r:0)
[11-03 11:14:54] [debug] Outbound: Sending CHANNEL_DATA (r:0, 9)
[11-03 11:14:54] [debug] Inbound: CHANNEL_DATA (r:0, 154)
[11-03 11:14:54] [debug] SFTP: Inbound: Received VERSION (v3, exts:posix-rename@openssh.com,statvfs@openssh.com,fstatvfs@openssh.com,hardlink@openssh.com,fsync@openssh.com)
[11-03 11:14:54] [debug] Outbound: Sending DISCONNECT (11)
[11-03 11:14:54] [error] TypeError: Cannot read property 'open' of undefined
	at d._limitSftpFileDescriptor (c:\Users\admin\.vscode\extensions\natizyskunk.sftp-1.15.6\dist\extension.js:61:99633)
	at d.<anonymous> (c:\Users\admin\.vscode\extensions\natizyskunk.sftp-1.15.6\dist\extension.js:61:99472)
	at Generator.next (<anonymous>)
	at s (c:\Users\admin\.vscode\extensions\natizyskunk.sftp-1.15.6\dist\extension.js:61:97522)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) 
[11-03 11:14:54] [debug] Socket ended
[11-03 11:14:54] [debug] Socket closed

**To Reproduce**
1、upload a file

**Expected behavior**
we can upload file

**Desktop (please complete the following information):**
 - OS: [Win10]
 - VSCode Version [e.g. 1.61.2]
 - Extension Version [e.g. 1.15.6]

**Extension Logs from Startup** - *required*
  1.  Open User Settings.

      * On Windows/Linux - File > Preferences > Settings
      * On macOS - Code > Preferences > Settings
  2. Set `sftp.debug` to `true` and reload vscode.
  3. Reproduce the problem, get the logs from View > Output > sftp.

**Comment by Natizyskunk** [comment]
As i can see, it seems that you've not correctly set the filepath to your `.ssh` folder and `config` file inside you `SFTP.json` config file.
The error indicate `C:\Users\admin.ssh\config` but it should be `C:\Users\admin\.ssh\config`. Notice the backslash before the `.ssh` folder. It should look like this : 
```json
{
    "name": "<connection_name>",
    "host": "<hostname_or_IP>",
    "protocol": "sftp",
    "port": <SSH_port>,
    "username": "<username>",
    "privateKeyPath": "<private_key_path>",
    "remotePath": "<remote_path>"
}
```

Example : 
```json
{
    "name": "example.com",
    "host": "example.com",
    "protocol": "sftp",
    "port": 22,
    "username": "my_username",
    "privateKeyPath": "C:\\Users\\admin\\.ssh\\id_rsa",
    "remotePath": "/var/www/html"
}
```

Now please also verify that the `config` file actually exist. If not just create it in `C:\Users\admin\.ssh` and add this inside it : 
```
PubkeyAcceptedKeyTypes=+ssh-dss

Host <host_to_connect>
    HostName <hostname_or_IP>
    User <username>
    # Port is optional (22 by default)
    Port <SSH_port>
    # If you're using an ssh private_key add this
    IdentityFile <private_key_path>
```

Example : 
```
PubkeyAcceptedKeyTypes=+ssh-dss

Host example.com
    HostName example.com
    User my_username
    Port 22
    IdentityFile ~/.ssh/id_rsa
```

In my example `~` mean current user folder. So `~/.ssh/id_rsa` is the same as `C:/Users/admin/.ssh/id_rsa`.

Please let me know if this has fixed your problem.
