### ISSUE TITLE
Fail connect to server

### ISSUE THREAD

**Issue by DacTT-99** [Natizyskunk/vscode-sftp#88]
**Do you read the FAQ?**
- [x] Yes.

**Describe the bug**
I can ssh connect to server via terminal : ssh -t efgh@abcd -p 22 -i "/home/list_99/.ssh/id_rsa"
But when connecting by "Open SSH in Terminal" : ssh -t efgh@192.10.4.00 -p 22 -i "/home/list_99/.ssh/id_rsa"
it make "time out"

How can I use hostname alternative IP to connect?

My .shh/config

StrictHostKeyChecking=no
Host *
    ServerAliveInterval 300
    ServerAliveCountMax 6
    ForwardAgent yes
Host abcd
Hostname 192.10.4.00
User efgh
Port 22

Host abcd2
Hostname 192.10.4.00
User efgh
Port 10322

sftp.config
{
    "name": "Server1",
    "host": "abcd",
    "protocol": "sftp",
    "port": 22,
    "username": "efgh",
    "remotePath": "/home/efgh/workspace",
    "uploadOnSave": false,
    "useTempFile": true,
    "openSsh": true,
    "privateKeyPath":"/home/list_99/.ssh/id_rsa",
    "sshConfigPath":"/home/list_99/.ssh/config",
    "connectTimeout": 20000
}

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - VSCode Version 1.62.2
 - Extension Version 1.15.8

**Extension Logs from Startup** - *required*
 [11-17 10:00:58] [trace] run command 'Download Project'
[11-17 10:00:58] [trace] handle download folder for /home/list_99/workspace_local
[11-17 10:00:58] [debug] Custom crypto binding not available
[11-17 10:00:58] [debug] Local ident: 'SSH-2.0-ssh2js1.5.0'
[11-17 10:00:58] [debug] Client: Trying 192.10.4.00 on port 22 ...
[11-17 10:01:18] [debug] Outbound: Sending DISCONNECT (11)
[11-17 10:01:18] [error] Error: [192.10.4.00]: Timed out while waiting for handshake
	at Client.<anonymous> (/home/list_99/.vscode/extensions/natizyskunk.sftp-1.15.8/dist/extension.js:2:242528)
	at Client.emit (events.js:327:22)
	at Timeout._onTimeout (/home/list_99/.vscode/extensions/natizyskunk.sftp-1.15.8/node_modules/ssh2/lib/client.js:1016:16)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7) 
[11-17 10:01:18] [debug] Socket closed

**Comment by robertzas** [comment]
Also having this issue on wsl and windows. Seems like the new update to vscode killed it.

**Comment by Natizyskunk** [comment]
@DacTT-99, @robertzas,

Can you guys retry with the latest [v1.15.9](https://github.com/Natizyskunk/vscode-sftp/releases/tag/v1.15.9) release please ? It should remove the bug.

**Comment by robertzas** [comment]
Now everything is working as expected. TYVM.
